### ISSUE TITLE
persist_to_workspace docs are inconsistent

### ISSUE THREAD

**Issue by frewsxcv** [circleci/circleci-docs#1212]
https://circleci.com/docs/2.0/configuration-reference/#attach_workspace

```yaml
- persist_to_workspace:
    paths: /tmp/file-name
```

-----------

https://circleci.com/docs/2.0/workflows/

```yaml
      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output
```

-----------

what is `root`? should it be documented in the configuration page? is `paths` a string or list?
