### ISSUE TITLE
What is keyword `defaults` used to define reusable templates?

### ISSUE THREAD

**Issue by kenden** [circleci/circleci-docs#1280]
This issue is about <https://circleci.com/docs/2.0/workflows/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/workflows.md>)

In this section:
https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs

There is the example:
```
defaults: &defaults
  working_directory: /tmp
  docker:
    - image: buildpack-deps:jessie

version: 2
jobs:
  flow:
    <<: *defaults
    steps:
      - run: mkdir -p workspace
      - run: echo "Hello, world!" > workspace/echo-output

      - persist_to_workspace:
          # Must be relative path from working_directory
          root: workspace
	  # Must be relative path from root
          paths:
            - echo-output

  downstream:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

      - run: |
          if [[ `cat /tmp/workspace/echo-output` == "Hello, world!" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  version: 2

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow
```

On the very first line:
```
defaults: &defaults
```

Where is the first word, `defaults`, coming from? Does it always need to be `defaults`?
Or can it also be whatever I define?
```
deploytemplate: &deploytemplate
or
defaults: &deploytemplate
or
whatever: &deploytemplate
or maybe this:
default:
  - &deploytemplate
  - &gittagtemplate
  - &onemoretemplate
```
