### ISSUE TITLE
setup-heroku.sh script fails

### ISSUE THREAD

**Issue by winstonwolff** [circleci/circleci-docs#1413]
This issue is about <https://circleci.com/docs/2.0/project-walkthrough/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/project-walkthrough.md>)

The line `tar -xvzf heroku-linux-amd64.tar.gz -C /usr/local/lib` does not work. Investigating with SSH indicates the circleci user does not have write permissions in /usr/local.

**Comment by sha1sum** [comment]
Hi @winstonwolff -- This is odd because the CircleCI builds are fine, so I decided to run the commands from the demo repo's CircleCI config, and I did not see any issue. Could you tell me what environment you're running this on? Also, what Docker image are you using as your base?

Here's the output of the commands:

```
└─❱❱❱ docker run -it python:3.6.0 bash                                                                                                                                                                +693 8:05 ❰─┘
root@c2a1642bc6f4:/# git clone https://github.com/CircleCI-Public/circleci-demo-python-flask ~/circulate
Cloning into '/root/circulate'...
remote: Counting objects: 129, done.
remote: Total 129 (delta 0), reused 0 (delta 0), pack-reused 129
Receiving objects: 100% (129/129), 4.03 MiB | 4.48 MiB/s, done.
Resolving deltas: 100% (39/39), done.
Checking connectivity... done.
root@c2a1642bc6f4:/# cd ~/circulate
root@c2a1642bc6f4:~/circulate# python3 -m venv venv
root@c2a1642bc6f4:~/circulate# . venv/bin/activate
(venv) root@c2a1642bc6f4:~/circulate# pip install -r requirements/dev.txt
Collecting Flask==0.12 (from -r requirements/common.txt (line 1))
  Downloading Flask-0.12-py2.py3-none-any.whl (82kB)
    100% |████████████████████████████████| 92kB 1.5MB/s
Collecting Flask-Bootstrap==3.3.7.1 (from -r requirements/common.txt (line 2))
  Downloading Flask-Bootstrap-3.3.7.1.tar.gz (456kB)
    100% |████████████████████████████████| 460kB 2.9MB/s
Collecting Flask-HTTPAuth==3.2.2 (from -r requirements/common.txt (line 3))
  Downloading Flask-HTTPAuth-3.2.2.tar.gz
Collecting Flask-Login==0.4.0 (from -r requirements/common.txt (line 4))
  Downloading Flask_Login-0.4.0-py2.py3-none-any.whl
Collecting Flask-Mail==0.9.1 (from -r requirements/common.txt (line 5))
  Downloading Flask-Mail-0.9.1.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 886kB/s
Collecting Flask-Migrate==2.0.3 (from -r requirements/common.txt (line 6))
  Downloading Flask-Migrate-2.0.3.tar.gz
Collecting Flask-Moment==0.5.1 (from -r requirements/common.txt (line 7))
  Downloading Flask-Moment-0.5.1.tar.gz
Collecting Flask-PageDown==0.2.2 (from -r requirements/common.txt (line 8))
  Downloading Flask-PageDown-0.2.2.tar.gz
Collecting Flask-SQLAlchemy==2.2 (from -r requirements/common.txt (line 9))
  Downloading Flask_SQLAlchemy-2.2-py2.py3-none-any.whl
Collecting Flask-Script==2.0.5 (from -r requirements/common.txt (line 10))
  Downloading Flask-Script-2.0.5.tar.gz (42kB)
    100% |████████████████████████████████| 51kB 5.2MB/s
Collecting Flask-WTF==0.14.2 (from -r requirements/common.txt (line 11))
  Downloading Flask_WTF-0.14.2-py2.py3-none-any.whl
Collecting Jinja2==2.9.5 (from -r requirements/common.txt (line 12))
  Downloading Jinja2-2.9.5-py2.py3-none-any.whl (340kB)
    100% |████████████████████████████████| 348kB 2.6MB/s
Collecting Mako==1.0.6 (from -r requirements/common.txt (line 13))
  Downloading Mako-1.0.6.tar.gz (575kB)
    100% |████████████████████████████████| 583kB 2.3MB/s
Collecting Markdown==2.6.8 (from -r requirements/common.txt (line 14))
  Downloading Markdown-2.6.8.tar.gz (307kB)
    100% |████████████████████████████████| 317kB 4.0MB/s
Collecting MarkupSafe==1.0 (from -r requirements/common.txt (line 15))
  Downloading MarkupSafe-1.0.tar.gz
Collecting psycopg2==2.7 (from -r requirements/common.txt (line 16))
  Downloading psycopg2-2.7-cp36-cp36m-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 803kB/s
Collecting SQLAlchemy==1.1.6 (from -r requirements/common.txt (line 17))
  Downloading SQLAlchemy-1.1.6.tar.gz (5.2MB)
    100% |████████████████████████████████| 5.2MB 308kB/s
Collecting WTForms==2.1 (from -r requirements/common.txt (line 18))
  Downloading WTForms-2.1.zip (553kB)
    100% |████████████████████████████████| 563kB 2.6MB/s
Collecting Werkzeug==0.11.15 (from -r requirements/common.txt (line 19))
  Downloading Werkzeug-0.11.15-py2.py3-none-any.whl (307kB)
    100% |████████████████████████████████| 317kB 4.0MB/s
Collecting alembic==0.9.1 (from -r requirements/common.txt (line 20))
  Downloading alembic-0.9.1.tar.gz (999kB)
    100% |████████████████████████████████| 1.0MB 1.4MB/s
Collecting bleach==2.0.0 (from -r requirements/common.txt (line 21))
  Downloading bleach-2.0.0-py2.py3-none-any.whl
Collecting blinker==1.4 (from -r requirements/common.txt (line 22))
  Downloading blinker-1.4.tar.gz (111kB)
    100% |████████████████████████████████| 112kB 8.4MB/s
Collecting html5lib==1.0b10 (from -r requirements/common.txt (line 23))
  Downloading html5lib-1.0b10-py2.py3-none-any.whl (112kB)
    100% |████████████████████████████████| 112kB 3.5MB/s
Collecting itsdangerous==0.24 (from -r requirements/common.txt (line 24))
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 9.0MB/s
Collecting six==1.10.0 (from -r requirements/common.txt (line 25))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting ForgeryPy==0.1 (from -r requirements/dev.txt (line 2))
  Downloading ForgeryPy-0.1.tar.gz
Collecting Pygments==2.2.0 (from -r requirements/dev.txt (line 3))
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |████████████████████████████████| 849kB 1.9MB/s
Collecting colorama==0.3.7 (from -r requirements/dev.txt (line 4))
  Downloading colorama-0.3.7-py2.py3-none-any.whl
Collecting coverage==4.3.4 (from -r requirements/dev.txt (line 5))
  Downloading coverage-4.3.4-cp36-cp36m-manylinux1_x86_64.whl (191kB)
    100% |████████████████████████████████| 194kB 6.1MB/s
Collecting httpie==0.9.9 (from -r requirements/dev.txt (line 6))
  Downloading httpie-0.9.9-py2.py3-none-any.whl (74kB)
    100% |████████████████████████████████| 81kB 6.5MB/s
Collecting requests==2.13.0 (from -r requirements/dev.txt (line 7))
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |████████████████████████████████| 593kB 2.5MB/s
Collecting selenium==3.3.0 (from -r requirements/dev.txt (line 8))
  Downloading selenium-3.3.0-py2.py3-none-any.whl (925kB)
    100% |████████████████████████████████| 931kB 1.2MB/s
Collecting unittest-xml-reporting==2.1.0 (from -r requirements/dev.txt (line 9))
  Downloading unittest_xml_reporting-2.1.0-py2.py3-none-any.whl
Collecting click>=2.0 (from Flask==0.12->-r requirements/common.txt (line 1))
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 6.1MB/s
Collecting dominate (from Flask-Bootstrap==3.3.7.1->-r requirements/common.txt (line 2))
  Downloading dominate-2.3.1.tar.gz
Collecting visitor (from Flask-Bootstrap==3.3.7.1->-r requirements/common.txt (line 2))
  Downloading visitor-0.1.3.tar.gz
Collecting python-editor>=0.3 (from alembic==0.9.1->-r requirements/common.txt (line 20))
  Downloading python-editor-1.0.3.tar.gz
Collecting webencodings (from html5lib==1.0b10->-r requirements/common.txt (line 23))
  Downloading webencodings-0.5.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=18.5 in ./venv/lib/python3.6/site-packages (from html5lib==1.0b10->-r requirements/common.txt (line 23))
Installing collected packages: Werkzeug, click, MarkupSafe, Jinja2, itsdangerous, Flask, dominate, visitor, Flask-Bootstrap, Flask-HTTPAuth, Flask-Login, blinker, Flask-Mail, SQLAlchemy, Flask-SQLAlchemy, Mako, python-editor, alembic, Flask-Script, Flask-Migrate, Flask-Moment, WTForms, Flask-PageDown, Flask-WTF, Markdown, psycopg2, six, webencodings, html5lib, bleach, ForgeryPy, Pygments, colorama, coverage, requests, httpie, selenium, unittest-xml-reporting
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for itsdangerous ... done
  Running setup.py install for dominate ... done
  Running setup.py install for visitor ... done
  Running setup.py install for Flask-Bootstrap ... done
  Running setup.py install for Flask-HTTPAuth ... done
  Running setup.py install for blinker ... done
  Running setup.py install for Flask-Mail ... done
  Running setup.py install for SQLAlchemy ... done
  Running setup.py install for Mako ... done
  Running setup.py install for python-editor ... done
  Running setup.py install for alembic ... done
  Running setup.py install for Flask-Script ... done
  Running setup.py install for Flask-Migrate ... done
  Running setup.py install for Flask-Moment ... done
  Running setup.py install for WTForms ... done
  Running setup.py install for Flask-PageDown ... done
  Running setup.py install for Markdown ... done
  Running setup.py install for ForgeryPy ... done
Successfully installed Flask-0.12 Flask-Bootstrap-3.3.7.1 Flask-HTTPAuth-3.2.2 Flask-Login-0.4.0 Flask-Mail-0.9.1 Flask-Migrate-2.0.3 Flask-Moment-0.5.1 Flask-PageDown-0.2.2 Flask-SQLAlchemy-2.2 Flask-Script-2.0.5 Flask-WTF-0.14.2 ForgeryPy-0.1 Jinja2-2.9.5 Mako-1.0.6 Markdown-2.6.8 MarkupSafe-1.0 Pygments-2.2.0 SQLAlchemy-1.1.6 WTForms-2.1 Werkzeug-0.11.15 alembic-0.9.1 bleach-2.0.0 blinker-1.4 click-6.7 colorama-0.3.7 coverage-4.3.4 dominate-2.3.1 html5lib-1.0b10 httpie-0.9.9 itsdangerous-0.24 psycopg2-2.7 python-editor-1.0.3 requests-2.13.0 selenium-3.3.0 six-1.10.0 unittest-xml-reporting-2.1.0 visitor-0.1.3 webencodings-0.5.1
(venv) root@c2a1642bc6f4:~/circulate# bash .circleci/setup-heroku.sh
--2017-08-10 12:07:27--  https://cli-assets.heroku.com/branches/stable/heroku-linux-amd64.tar.gz
Resolving cli-assets.heroku.com (cli-assets.heroku.com)... 54.230.19.184, 54.230.19.77, 54.230.19.156, ...
Connecting to cli-assets.heroku.com (cli-assets.heroku.com)|54.230.19.184|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21425775 (20M) [application/x-tar]
Saving to: ‘heroku-linux-amd64.tar.gz’

heroku-linux-amd64.tar.gz                            100%[========================================================================================================================>]  20.43M  9.61MB/s   in 2.1s

2017-08-10 12:07:30 (9.61 MB/s) - ‘heroku-linux-amd64.tar.gz’ saved [21425775/21425775]

heroku/
heroku/README
heroku/install
heroku/lib/
heroku/lib/npm/
heroku/lib/npm/.github/
heroku/lib/npm/.github/issue_template.md
heroku/lib/npm/.gitignore
heroku/lib/npm/.mailmap
heroku/lib/npm/.npmignore
...[TRUNCATED]...
```

The long list of files at the end of the output are from the command of which you speak.

**Comment by winstonwolff** [comment]
Hi Anthony—

I'm using `circleci/ruby:2.4.1-node-browsers` and if I recall from yesterday, the owner of /usr/local/lib was user 500 which was not the "circleci" user. Perhaps it's a permission problem with the image, not the script. Either-or I suppose.  I worked around it by untaring the heroku tool to the home directory and adding that to my path.

If this helps, here's my config.yml:

```
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          DATABASE_URL: "postgres://prep_dst@localhost/prep_test"
          RAILS_ENV: test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: XXX
          POSTGRES_DB: XXX
          POSTGRES_PASSWORD: XXX

    working_directory: ~/repo

    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: v2-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: v2-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Database setup
      - run: bundle exec rake db:create db:schema:load db:seed

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results

      # Deploy to Heroku
      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - XXX
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master --force
              $HOME/heroku/bin/heroku restart
            fi
```
