### ISSUE TITLE
interpolating-environment-variables section is incomplete:

### ISSUE THREAD

**Issue by kenden** [circleci/circleci-docs#1675]
This issue is about <https://circleci.com/docs/2.0/env-vars/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/env-vars.md>)

The [interpolating-environment-variables section](https://circleci.com/docs/2.0/env-vars/#interpolating-environment-variables-to-set-other-environment-variables) is incomplete:

This section says to do it in bash with:
```
- run: echo 'export PATH=/foo/bin:$PATH' >> $BASH_ENV
```

However, it seems to work fine when setting the environment on the job level, and ***not*** under docker:
Ex:

```
version: 2
jobs:
  build:
    docker:
      - image: golang:1.8-alpine
    environment:
      TAG: v${CIRCLE_BUILD_NUM}
```

The `TAG` created from another environment variable and is available to all steps in the build job... Is this missing from the documentation or is it an undocumented feature?
