### ISSUE TITLE
Removing username - password auth step works

### ISSUE THREAD

**Issue by hyprstack** [circleci/circleci-docs#1782]
This issue is about <https://circleci.com/docs/2.0/google-container-engine/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/google-container-engine.md>)

When trying to upload a cloud function using this guide, although I had a service account json key with the appropriate permissions to upload a cloud function, the step where

```
    auth:
    #Put the contents of keyfile.json into an environment variable for the build called GCR_CREDS, which is then passed in.
      username: _json_key
      password: $GOOGLE_AUTH 
```

failed constantly in `circle ci` with the error message 

```
Build-agent version 0.0.4545-ba6be34 (2017-11-20T20:01:46+0000)
Downloading previous test results
Starting container google/cloud-sdk:latest
  image is cached as google/cloud-sdk:latest, but refreshing...
Error response from daemon: Get https://registry-1.docker.io/v2/google/cloud-sdk/manifests/latest: unauthorized: incorrect username or password
```

I found that removing `auth: ...` completely from the config file solved my problem.

Also explaining whether the comment ` #Put the contents of keyfile.json into an environment variable for the build called GCR_CREDS, which is then passed in.` is relevant would be good too.

Perhaps an explanation to what `_json_key` as username does would be helpful too as I also spent a lot of time replacing it, to no avail, in the hopes of getting the docs to work.
