### ISSUE TITLE
Be more specific about how cache writes and fallbacks interact

### ISSUE THREAD

**Issue by jfirebaugh** [circleci/circleci-docs#1862]
This issue is about <https://circleci.com/docs/2.0/caching/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/caching.md>)

I'd appreciate some clarification about how cache writes and prefix matching interact. Specifically, given the following:

```
      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ arch }}-{{ .Branch }}
            - gem-cache
            
      - run: bundle install --path vendor/bundle
      
      - save_cache:
          key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
```

If the restore step finds no matches in the first two keys, but several potential matches with the prefix `gem-cache`, which one is chosen? (I'm hoping it's most recently written.)
