### ISSUE TITLE
Incorrect example for docker_layer_caching with machine executor

### ISSUE THREAD

**Issue by joshowen** [circleci/circleci-docs#1865]
This issue is about <https://circleci.com/docs/2.0/docker-layer-caching/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/docker-layer-caching.md>)

The wording for the Machine executor is incorrect.  There isn't a `- machine` step supported.  I think the correct example would be:
```
version: 2
jobs:
    build:
        machine:
          docker_layer_caching: true
    steps:
        ...
```
