### ISSUE TITLE
Elixir, junit & cache

### ISSUE THREAD

**Issue by ericsullivan** [circleci/circleci-docs#1911]
This issue is about <https://circleci.com/docs/2.0/language-elixir/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/language-elixir.md>)

I had to pull info from a few sources and was hoping to share some of my findings in case they'd help others. I didn't want to open a PR directly, as I'm not sure how much of this code you'd like to put into the documentation. I'm also not sure how great it is, as I just started using CircleCI :) Thank you

config.yml

```
version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.5
        environment:
          MIX_ENV: test
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD:

    working_directory: ~/app

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: mix test

      - store_test_results:
          path: _build/test/junit
```

To get junit working I had to update my deps w/
```
{:junit_formatter, ">= 0.0.0", only: :test},
```

And test_helper.ex
```
junit_folder = Mix.Project.build_path() <> "/junit/#{Mix.Project.config[:app]}"
File.mkdir_p!(junit_folder)
:ok = Application.put_env(:junit_formatter, :report_dir, junit_folder)

ExUnit.configure formatters: [JUnitFormatter, ExUnit.CLIFormatter]
ExUnit.start()
```

I was testing an umbrella application, so I needed to add that helper to each application.

The cache code was taken from here: http://joeellis.la/using-circle-2-0-with-elixir/
