### ISSUE TITLE
Allow exact branch names to be used for filtering in scheduled workflow

### ISSUE THREAD

**Issue by AndrewThompsonBluetel** [circleci/circleci-docs#1915]
In the example below, the scheduled workflow will not run due to the branch filter. We assume this is due to the `/` in the name. Could we get some clarification of whether this is intended? If so could it be added to the docs?
```
scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only: feature/test-123

    jobs:
      - build
```
