### ISSUE TITLE
Circle2.0 docs for asset caching are confusing

### ISSUE THREAD

**Issue by bwebster** [circleci/circleci-docs#2073]
As a follow-on to https://github.com/circleci/circleci-docs/issues/1102, the [2.0 docs around saving and restoring the cache](https://circleci.com/docs/2.0/caching/#full-example-of-saving-and-restoring-cache) refer to a mysterious `VERSION`.  Can you clarify what this should be?

**Comment by smart-alek** [comment]
Hey @bwebster and @simoniong (from #1102)!

Great question, thanks for calling this out. Because this configuration was pulled from Discuss, odds are that the creator was generating a `VERSION` file for their Rails application, then using that to generate cache keys. They're probably doing something [along these lines](https://stackoverflow.com/questions/9073446/where-do-you-store-your-rails-applications-version-number) and then saving the results to a file.

But! The actual file is less important than the fact that the file (a) exists in your repository and (b) doesn't change between saving/restoring the cache. That's why the earlier caching step is using `Gemfile.lock` for caching dependencies.

I'm going to replace the cache keys with a variant of something we're using in our [workflows example](https://github.com/CircleCI-Public/circleci-demo-workflows/blob/fan-in-fan-out/.circleci/config.yml):

```yaml
- save_cache:
    keys:
      - v1-assets-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - v1-assets-{{ arch }}-{{ .Branch }}
      - v1-assets
```

Let me know if that makes sense! PR is incoming as well.... :)
