### ISSUE TITLE
Google Cloud Service key JSON should not be encoded in base64 using custom image

### ISSUE THREAD

**Issue by m-nakamura145** [circleci/circleci-docs#2193]
I wanted to use the custom image hosted on the GCR as the base image of CircleCI 2.0.
so, I saw [this document](https://circleci.com/docs/2.0/google-container-engine/#authenticate-to-googles-container-registry) and created service account JSON key file. 

When I encoded JSON key file in base64 and set the encoded text to `GCLOUD_SERVICE_KEY` environment variable. CircleCI build faild due to `Unable to parse json key`

But, When I set raw JSON text to `GCLOUD_SERVICE_KEY` environment variable. CircleCI build succeeded!

```
version: 2
jobs:
  deploy-job:
    docker:
      - image: gcr.io/project/image-name
        auth:
          username: _json_key  # default username when using a JSON key file to authenticate
          password: $GCLOUD_SERVICE_KEY  # encoded service account you created
```

In this sample yaml file. I think `password` value should be raw JSON text. Is it wrong?

see: https://discuss.circleci.com/t/impossible-to-use-a-private-gcr-io-base-image-on-circle-2-0/15965

https://github.com/circleci/circleci-docs/pull/2142
