### ISSUE TITLE
Remove references to RSpec and Minitest in "Automatic test metadata collection" header (_cci1/test-metadata.md)

### ISSUE THREAD

**Issue by eric-hu** [circleci/circleci-docs#225]
When Ruby users on Minitest want to manually enable parallelization for their builds, they need to specify the test reports folder or our autobalancing won't work for them.

In our [test-metadata](https://circleci.com/docs/test-metadata/) docs, we recommend minitest-ci, which is a gem we own.  We don't document that you have to pass in a flag to set the autobalance folder.  Users can do that with a setup like the following:

```
test:
  override:
    - bundle exec rake test TESTOPTS="--ci-dir=$CIRCLE_TEST_REPORTS":
        parallel: true
        files:
          - test/**/*.rb
```

I'm not sure if this should go in the test-metadata page, the parallel manual setup page, or both.  Any thoughts?

I've just added it to the minitest-ci gem home page as well, but I have a feeling many users will only use
