### ISSUE TITLE
Inconsistencies CircleCI Local CLI and Online version

### ISSUE THREAD

**Issue by Rhuansantos** [circleci/circleci-docs#2278]
This issue is about <https://circleci.com/docs/2.0/local-cli/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/local-cli.md>)

Hi, I have been facing some inconsistencies when trying to use mocha and chai to run my tests. 
Using the CircleCI Local CLI my tests are successful, however, on the online version the same tests are falling.

```````

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.10
        environment:
          PGHOST: 127.0.0.1
          PGUSER: rhuan
          NODE_ENV: test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: bilibiosTesting
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: rhuan
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install
      - run: yarn global add sequelize-cli
      - run: cd api/db && ../../node_modules/.bin/sequelize db:migrate
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn run test

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    #environment:
    steps:
      - checkout
      - run: bash deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: dev

`````````

Result using the CircleCI Local CLI

<img width="1440" alt="screen shot 2018-04-20 at 4 25 22 am" src="https://user-images.githubusercontent.com/2942805/39040219-e40f7b2c-4454-11e8-8cea-fda4fa37bfdf.png">

Result using Circle Ci online

![screen shot 2018-04-20 at 4 40 41 am](https://user-images.githubusercontent.com/2942805/39040342-18d012f4-4455-11e8-9831-c207b30387a9.png)

**Note**: running mocha and chai without circle Ci the tests are also successful, I have tried multiple ports but the tests on the online version keeps falling

Thanks!
