### ISSUE TITLE
Inconsistent example config for bundle install

### ISSUE THREAD

**Issue by JasonBarnabe** [circleci/circleci-docs#2289]
In https://circleci.com/docs/2.0/language-ruby/, in the full configuration section, the bundle install command is:

```yml
      - run:
          name: Bundle Install
          command: bundle check || bundle install
```

Later, when each section is broken down and explained, it's given as

```yml
  - run:
      name: Bundle Install
      command: bundle install --path vendor/bundle
```

I'm not sure which is right.
