### ISSUE TITLE
setting up cloud circleci to build cuda project

### ISSUE THREAD

**Issue by Data-drone** [circleci/circleci-docs#2302]
There doesn't seem to be any docs on how to specify a gpu machine for building cuda or can I just go:

```
version: 2
jobs: 
  build:
    machine:
       image: nvidia/cuda:8.0-devel
    steps:

       - checkout

    ...

```

Thanks
