### ISSUE TITLE
need example of CIRCLE_INTERNAL_TASK_DATA

### ISSUE THREAD

**Issue by michelle-luna** [circleci/circleci-docs#2327]
Are there any examples of anyone using timing data via CIRCLE_INTERNAL_TASK_DATA? I've searched the discuss, the github, the web, and cannot find nary a one. Just a few mentions. (I also commented in #1598)

**Comment by bf4** [comment]
@michelle-luna I agree about not finding much. Here's what I'm doing

Noted in https://discuss.circleci.com/t/problem-using-split-by-timings-in-workflows/14780/8
Also see https://discuss.circleci.com/t/rails-5-with-2-0-cant-run-rspec-using-multiple-containers/16665/4

```diff
 jobs:
   checkout_code:
       - save_cache:
           key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
           paths:
             - ~/server
+      # Copy and persist .circleci-task-data from first container to make test timings work
+      - run:
+          command: |
+            sudo mkdir -p "${CIRCLE_INTERNAL_TASK_DATA:-/.circleci-task-data}"
+            mkdir -p tmp/circleci-task-data
+            cp -R "${CIRCLE_INTERNAL_TASK_DATA:-/.circleci-task-data}" tmp/circleci-task-data/
+      - persist_to_workspace:
+          root: .
+          paths:
+            - tmp/circleci-task-data
```

```diff
+  test_all:
     <<: *container_config
+    parallelism: 2
     steps:
       - *restore_repo
       - *restore_bundle
+      - attach_workspace:
+              at: ~/server
+      # Copy over persisted .circleci-task-data
+      - run:
+          command: |
+            mkdir -p tmp/circleci-task-data
+            touch tmp/circleci-task-data/here_be_dragons
+            sudo mkdir -p "${CIRCLE_INTERNAL_TASK_DATA:-/.circleci-task-data}"
+            sudo cp -R tmp/circleci-task-data/* "${CIRCLE_INTERNAL_TASK_DATA:-/.circleci-task-data}/"
```

```diff
+          name: Run Tests
           command: |
-            bin/rspec --format documentation --no-color --format RspecJunitFormatter --out tmp/rspec/rspec.xml
+            mkdir -p tmp/rspec # Create JUnit report dir
+            if [ "${CIRCLE_NODE_TOTAL:-1}" == "1" ]; then
+              bin/rspec --format documentation --no-color --format RspecJunitFormatter \
+                --out "tmp/rspec/rspec-all.xml"
+            else
+              circleci tests glob "spec/**/*_spec.rb" > test_files.txt
+              cat test_files.txt | circleci tests split --split-by=timings > split_test_files.txt
+              TESTFILES="$(cat split_test_files.txt | xargs)"
+              if [ -z "$TESTFILES" ]; then echo  'No tests are scheduled to be executed on this node'; exit 0; fi
+              export SPEC="$TESTFILES"
+              export SPEC_OPTS="--format documentation --format RspecJunitFormatter --out tmp/rspec/rspec-${CIRCLE_NODE_INDEX:-0}.xml"
+              bin/rake spec
+              mkdir -p tmp/circleci-task-data
+              sudo mkdir -p "${CIRCLE_INTERNAL_TASK_DATA:-/.circleci-task-data}"
+              # Copy .circleci-task-data timings to test result cache
+              cp -R "${CIRCLE_INTERNAL_TASK_DATA:-/.circleci-task-data}" tmp/circleci-task-data/
+            fi
           no_output_timeout: 60s
           when: on_success
       - store_test_results:
           path: tmp/rspec
+      - store_test_results:
+          path: tmp/circleci-task-data
```

no idea if this is what's intended.

**Comment by smart-alek** [comment]
@bf4 I'm late to the party, but just wanted to get some clarity on what you need here. :)

My understanding of `CIRCLE_INTERNAL_TASK_DATA` is that it's just the directory where test timing data can be found. From [this document](https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-by-timings), CircleCI is automatically saving timing data into that directory. But I'm not sure that you need to be **making** a directory per executor; more like you have access to this directory, so you can `cat` the results as a part of your build process.

Then! There's an **other** bit about using the `store_test_results` key to actually **save** the timing data. [Some nuances](https://circleci.com/docs/2.0/configuration-reference/#store_test_results) apply to the process of doing that.

But! I'm in communication with one of our support folks, so we can get clarity on this and see what we can do to make this clearer in the docs. Thanks for your patience! :)

**Comment by bf4** [comment]
@smart-alek your understanding or your experience? Don't trust docs when users report issues :)

**Comment by bf4** [comment]
https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-by-timings

> CircleCI automatically saves timing data from previous successful runs to a default location ($CIRCLE_INTERNAL_TASK_DATA/circle-test-results). Ensure you are using the [store_test_results key](https://circleci.com/docs/2.0/configuration-reference/#store_test_results) to save your timing data, or there will be no historical data available.

meaning: timing results are automatically saved to a place that isn't automatically used across test runs.  CircleCI  recommends storing them with other test results, but doesn't mention how they are to be discovered and used in a subsequent run.

https://circleci.com/docs/2.0/configuration-reference/#store_test_results

> Special step used to upload test results so they display in builds’ Test Summary section and can be used for timing analysis. To also see test result as build artifacts, please use the store_artifacts step.

> Path to directory containing subdirectories of JUnit XML or Cucumber JSON test metadata files

> Note: Please write your tests to subdirectories of your store_test_results path, ideally named to match the names of your particular test suites, in order for CircleCI to correctly infer the names your reports.

meaning: the intention of the stored test results is for user-generated results. It seems like a hack for CircleCI generated data to need to be copied over

https://discuss.circleci.com/t/problem-using-split-by-timings-in-workflows/14780/8

There has been incompatibility of test timings being used along with the new workflows.

> The problem is that only the first container gets test timings so you can easily fix it on your own using workspace to pass it:

```
# Copy .circleci-task-data from first container to make test timings work
  - run: cp -R /.circleci-task-data tmp/circleci-task-data/

  - persist_to_workspace:
       root: .
       paths:
         - tmp/circleci-task-data
         - vendor/bundle
         - .bundle
Later just set them up into a proper place before running tests:

  - attach_workspace:
      at: /source

  # Copy .circleci-task-data from first container to make test timings work
  - run: cp -R tmp/circleci-task-data/* /.circleci-task-data/
```

> unfortunately that worked once and breaks now, no idea why. After playing with workflows today we abandoned them for now

someone then mentioned lack of workflow support for store_test_results https://github.com/circleci/circleci-docs/pull/1564

then @ryanwohara wrote:

> We have released support for timing-based test splitting within Workflows. Timing data will be made available from the most recent job (within the last 50) with the same job name.

meaning: from July 2017 through January 2018 the feature was effectively in a public beta 

There are other issues related to this
- https://github.com/circleci/circleci-docs/pull/1598 
- https://github.com/circleci/circleci-docs/issues/1771
- https://github.com/circleci/circleci-docs/pull/1841


Also:
https://discuss.circleci.com/t/rails-5-with-2-0-cant-run-rspec-using-multiple-containers/16665/4

@eric-hu wrote:

> So this issue is with the bash variable expansion. You’ll want to update the command to this:
```
bundle exec rspec --format progress \
                --format RspecJunitFormatter \
                --out /tmp/test-results/rspec.xml \
                --format progress \
                -- \
                $TEST_FILES
```

> Confirmed that the example Eric posted worked for me too. Thanks guys for the solution. @Eric, when is Circle going to stop giving out the wrong config to users setting up new projects?

**Comment by bf4** [comment]
Today on a branch I got 

> Requested historical based timing, but they are not present.  Falling back to name based sorting

Wish I knew why it wasn't present. I'm upgrading Rails in that branch.

It might be helpful if the circlei picard image were open sourced so we could see what it's doing. Looks like it's built from https://github.com/circleci/build-agent might be sending timing to datadog? The command is cmd/tests/split.go configured via cmd.yml it looksl ike

**Comment by smart-alek** [comment]
@bf4 thanks for your patience and **also** the diligent research you've presented in this thread! I don't have specific responses to anything you've written, but I do have other strange news:

Hot off the presses from one of our support engineers is [this PR](https://github.com/circleci/circleci-docs/pull/2345#pullrequestreview-121247758), which says that `CIRCLE_INTERNAL_TASK_DATA` doesn't even exist! I know this probably doesn't do anything for your original problem, but maybe it will at least get us back on the right track.

**Comment by sararead** [comment]
@bf4 @smart-alek The plot thickens! We changed the location of where these results are saved. The "doesn't exist" was a mistake on my side, I misread what we were doing there, my apologies on misdirecting this conversation! 

The new location is: `CIRCLE_INTERNAL_TASK_DATA=/.circleci-task-data`.

**Comment by bf4** [comment]
@sararead @smart-alek 
> The new location is: CIRCLE_INTERNAL_TASK_DATA=/.circleci-task-data.

That's what I have in my script https://github.com/circleci/circleci-docs/issues/2327#issuecomment-388932175

So, the genesis of this issue is that there are instructions for using this feature, but no complete examples of using it.  To my knowledge, my snippet, put together from various sources and trial and error, is the only one at this time, and it's still a bit of a hack.

Too bad https://github.com/circleci/picard-services/commit/14195162baca1243426ad0fb8fb0c93eda07f884 is private :(

**Comment by smart-alek** [comment]
@bf4 you have **succeeded** in getting our attention. :)

Our support team wants to escalate out of docs into a fully-fledged ticket. You've already met @sararead, but there will be other folks taking a look at this point. I'll keep this issue open until we figure out what we need to document on this end. Thanks for your patience!

**Comment by bf4** [comment]
@smart-alek :)

My take is individual issues are
- When is timing data available? Every job? Every workflow? Only first workflow?
- When is timing data generated? from the junit test result?
- How is timing data persisted? across branches? across workflows? across runs?
- How is timing data used?  Do I need to copy it from `.circleci-task-data`? Answer in part: `circleci tests glob "spec/**/*_spec.rb" > test_files.txt;  cat test_files.txt | circleci tests split --split-by=timings > split_test_files.txt; TESTFILES="$(cat split_test_files.txt | xargs)"`
- Can I see the raw data in a finished build?
- Can I use the raw data with other tools like 'knapsack'?
- What is done automatically and what require config.yml commands?
- How does parallelism affect timing usage?
- How can I debug why it might not be working?

On a Ruby-specific note, I ended up using Rake to load in the specified test files:
`export SPEC="$TESTFILES"``
`export SPEC_OPTS="--format documentation --format RspecJunitFormatter --out tmp/rspec/rspec-${CIRCLE_NODE_INDEX:-0}.xml"`
`bin/rake spec`

**Comment by ryanwohara** [comment]
> When is timing data available? Every job? Every workflow? Only first workflow?
Any given build where you've already stored them in a previous build. With Workflows the job names need to match.

> When is timing data generated? from the junit test result?
From your testing suite.

> How is timing data persisted? across branches? across workflows? across runs?
Per-project. With Workflows the job name also matters.

> How is timing data used?
Automatically when you use `circleci tests split --split-by=timings`

> Do I need to copy it
No

> Can I see the raw data in a finished build?
Just store it as an artifact and it will be accessible. Please note you can't reference an environment variable from `store_artifacts` step.

> Can I use the raw data with other tools like 'knapsack'?
Yes

> What is done automatically and what require config.yml commands?
Retrieving the test times _if they're available_ is automatic, but globbing the test files is manual.

> How does parallelism affect timing usage?
We allocate a fair number of files based on their time usage for a given container. It's not perfect in workflows yet, but it's pretty much perfect in a given 2.0 job without workflows.

> How can I debug why it might not be working?
Store your junit xml as an artifact, echo your test files before running them, and manually dig in to find out why things are inconsistent across jobs. One common issue is having rspec configured to re-run failing jobs, silently adding more more time to the build, and corrupting the timing data.

**Comment by bf4** [comment]
@ryanwohara Based on your response, it sounds like my minimal config for using workflows with only one job running tests would look like the below.

I've removed the attach/persist to workspace and any references to CIRCLE_INTERNAL_TASK_DATA (such as copying, saving, etc)


```yaml
version: 2.0
jobs:
  checkout_code:
    steps:
      - checkout
      <<: *container_config
      <<: *create_cache_diectories
      <<: *download_postgres_client
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

  bundle_dependencies:
    <<: *container_config
    steps:
      restore_cache:
        keys:
          - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      restore_cache:
        keys:
          - v2-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install RubyGems
          command: bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: v2-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  test_all:
     <<: *container_config
    parallelism: 2
    steps:
      restore_cache:
        keys:
          - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      restore_cache:
        keys:
          - v2-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      <<: *install_postgres_client
      - *wait_pg
      - run: bin/rake db:create db:structure:load
      - run:
          name: Run Tests
          command: |
            mkdir -p tmp/rspec # Create JUnit report dir
            circleci tests glob "spec/**/*_spec.rb" > test_files.txt
            cat test_files.txt | circleci tests split --split-by=timings > split_test_files.txt

            TESTFILES="$(cat split_test_files.txt | xargs)"
            if [ -z "$TESTFILES" ]; then echo  'No tests are scheduled to be executed on this node'; exit 0; fi

            export SPEC="$TESTFILES"
            export SPEC_OPTS="--format documentation --format RspecJunitFormatter --out tmp/rspec/rspec-${CIRCLE_NODE_INDEX:-0}.xml"

            bin/rake spec
          no_output_timeout: 60s
          when: on_success
      - store_test_results:
          path: tmp/rspec

  build:
    <<: *container_config
    steps:
      - *restore_repo
      - add_ssh_keys:
          fingerprints:
            - "ab:cd:ef:...."
      - run:
          name: "Deploy if master"
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              git push origin production --force
            else
              echo "Deploy job running on non-master branch '${CIRCLE_BRANCH}'"
              true
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - test_all:
          requires:
            - bundle_dependencies
      - build:
          requires:
            - test_all
```
