### ISSUE TITLE
New CircleCI 2.0 docs on deployment are missing section for "Deploy over SSH"

### ISSUE THREAD

**Issue by pirate** [circleci/circleci-docs#2332]
This issue is about <https://circleci.com/docs/2.0/deployment-integrations/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/deployment-integrations.md>)

A section should be added to describe how to "Deploy over SSH" using CircleCI 2.0, similar to the 1.0 docs: https://circleci.com/docs/1.0/introduction-to-continuous-deployment/#deploy-over-ssh

**Comment by pirate** [comment]
Suggested guide:


1. Add the SSH key for the server you're deploying to under `Project > Settings > SSH Permissions`
2. Add the env variables to your build VM for `SSH_USER` and `SSH_HOST` under `Project > Settings > Environment Variables` so you don't have to commit them in git
3. An example v2 yaml config for a simple SSH-based deploy workflow

```yaml
version: 2

jobs:
  build:
    ...

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh $SSH_USER@$SSH_HOST "<remote deploy command>"

workflows:
  version: 2
  build-and-deploy
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
```
