### ISSUE TITLE
CircleCi node does not run npm test as stated in docs

### ISSUE THREAD

**Issue by dman777** [circleci/circleci-docs#2357]
From https://circleci.com/docs/1.0/language-nodejs/#testing

> CircleCI will run npm test when you specify a test script in package.json. We also run your Mocha tests as well as run any test targets in Cakefiles or Makefiles.

This is not true. I have 

```
  "scripts": {
    "test": "./run-test.sh"
  },
```

And it is not running it. The impression I have it runs it automatically if the script exists. 

```
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.4.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
```
