### ISSUE TITLE
Important info is missing in api-job-trigger.md

### ISSUE THREAD

**Issue by sryabkov** [circleci/circleci-docs#2383]
This issue is about <https://circleci.com/docs/2.0/api-job-trigger/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/api-job-trigger.md>)

__Why this issue was opened__ The following was not clear to me until I did some experimenting. Documenting this on the page might save other people time.

Workflows cannot be triggered using the API, and the page does talk about this. However, even though my `config.yml` had a workflow definition, I was still able to add a new job to `config.yml`, and trigger it using the API. In my case, the workflow did not reference the new job, and I am not sure what would have happened if it did and if there were any downstream jobs. 

There is one important caveat. In our jobs referenced by the workflow, we were using contexts (as in https://circleci.com/docs/2.0/contexts/#creating-and-using-a-context). Environment variables defined in the context were not available when the new job was triggered using the API. The workaround we used was to re-define the environment variable on the project level instead of globally in the context. Because there is a very good UI for copying environment variables between projects, this is a very acceptable workaround.

**Comment by smart-alek** [comment]
Hey @sryabkov, thanks for reaching out!

I'm still a little unsure of what information you'd like more of (or what was unclear). Do you want an explicit statement about being able to trigger a non-Workflows job? Or a more prominent statement about not being able to trigger Workflows with the API?

Or is it more to do with the second paragraph, where you discuss the workaround for sharing environment variables with contexts/projects?

Definitely want to help here — I just need a bit of confirmation on what specifically you found lacking, so we can get it right. :) Thanks for your help!

**Comment by sryabkov** [comment]
@smart-alek Thanks and let me try to clarify:

- It was clear that it is not possible to trigger a _workflow_ using the API.
- It was NOT sufficiently clear that it is possible to trigger a _job_ using the API if that job was defined in `config.xml` that had the `workflows` section. __Suggestion:__ add the `workflows` section to the sample `config.yml` at the bottom of the page to illustrate that this scenario is possible.
- It was NOT clear at all that the job that is triggered via the API won't have access to environment variables defined in the referenced context, even if the job is referenced in the workflow

For example, to the last point, while experimenting, I tried this hack
```
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
      - build_demo:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /feature[\/_\.-].+/
          context: org-global
      - build_and_publish_demo_container:
          requires:
            - build_demo
          context: org-global
      - build_demo_on_request:
          # the following is a hack: we don't want to run the job as part of the worlflow
          # but we need to reference it in the workflow so that we can specify the context
          filters:
            branches:
              only:
                - non-existing-branch/non-existing-branch
          context: org-global
```

I managed to trigger `build_and_publish_demo_container` using the API, but it didn't get the env vars defined in `org-global`

Did I manage to clarify the issue?
