### ISSUE TITLE
question: Is there a way to set webhook notification from circleci?

### ISSUE THREAD

**Issue by ZouRui89** [circleci/circleci-docs#2411]
This issue is about <https://circleci.com/docs/2.0/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/index.md>)

Hi.
I am now developing a project on github, and circleci is used to run some of the basic tests.
A auto-robot is used to send comments on the pr pages, while CI fails.

In the code of our robot, we use ```mux.NewRouter().HandleFunc``` to handler webhook api.
For example, for ```register ping api```, there goes ```r.HandleFunc("/_ping", pingHandler).Methods("GET")```

I wonder is there a way to send webhook notification to our auto-robot, when tests on ```circleci``` fail.
I have went through your docs and did not get the info  i need.

So, is circleci supporting ```webhook notification``` now?

**Comment by smart-alek** [comment]
Hey @ZouRui89! Thanks for filing this issue!

So, this actually **is** documented in CircleCI 1.0, but it makes sense that you wouldn't have been able to find it. Head over to https://circleci.com/docs/1.0/configuration/#per-branch-notifications, and you should be able to get what you need from there.

But your bigger point — about documenting this in 2.0 — is a good one! We were thinking of tweaking this feature a little bit before officially documenting it in 2.0, but the fact that you needed this and couldn't find it is proof enough for me! :)

**Comment by ZouRui89** [comment]
Thx for your hints! But it should be https://circleci.com/docs/1.0/configuration/#notify.
Problem solved! 😄

**Comment by smart-alek** [comment]
@ZouRui89 Ah, whoops! I must have linked to the examples section, rather than the configuration spec. 😬 

I'm still going to leave this issue open; we knew that the `notify` feature worked on 2.0, but it's likely to change. We were waiting for things to calm down slightly before documenting in 2.0.

However! By filing this issue, you have provided us with the push we need. :)

**Comment by smart-alek** [comment]
@ZouRui89 just to update you: I spoke with our support team, and it looks like we're going to keep support for this feature limited to the 1.0 document until we have something properly ready for 2.0.

Thanks again for filing this issue!

**Comment by piotr-s-brainhub** [comment]
@smart-alek 
so how can I be obtain a webhook on CircleCI job end (both for success and failure)?
I found a way to do that in 2.0:
```
notify:
    webhooks:
      - url: https://some.url.com/circleci-hooks
```
However it's undocumented and it doesn't work for CircleCI 2.1.

**Comment by mloskot** [comment]
I can confirm https://github.com/circleci/circleci-docs/issues/2411#issuecomment-434947063 works. It's worth to declare MAJOR.MINOR version though: `version: 2.0`

**Comment by matthewhuang-camelot** [comment]
What's the official status on this?

**Comment by piotr-s-brainhub** [comment]
in CirclecCI 2.1 you can do this:
```
  notify_job_status:
    description: Send webhook to dmx-slackbot about job status
    steps:
      - run:
          name: On success
          when: on_success
          command: |
            curl https://slackbot.foo.bar.io/slack/circle-ci-notify -d '{"payload":{"reponame":"'"$CIRCLE_PROJECT_REPONAME"'","branch":"'"$CIRCLE_BRANCH"'","build_parameters":{"CIRCLE_JOB":"'"$CIRCLE_JOB"'"},"outcome":"fixed","build_url":"'"$CIRCLE_BUILD_URL"'"}}' -H "Content-Type: application/json" -X POST -i
      - run:
          name: On fail
          when: on_fail
          command: |
            curl https://slackbot.foo.bar.io/slack/circle-ci-notify -d '{"payload":{"reponame":"'"$CIRCLE_PROJECT_REPONAME"'","branch":"'"$CIRCLE_BRANCH"'","build_parameters":{"CIRCLE_JOB":"'"$CIRCLE_JOB"'"},"outcome":"failed","build_url":"'"$CIRCLE_BUILD_URL"'"}}' -H "Content-Type: application/json" -X POST -i
```

and append `- notify_job_status` at the end of each workflow

**Comment by nish-mdn** [comment]
@piotr-s-brainhub Can you please share complete circleci config file? i need a functionality of sending an email of success or failure messages for the each and every job status. will this work?

**Comment by QualityRobD** [comment]
Any updates on this one? I'm struggling as well.

Here is what I'm working with:
```
notify_teams: &notify_teams
    description: send webhook to teams
    steps:
        - run:
            name: Notify Teams of Failure
            when: on_fail
            webhooks:
                - url: https://outlook.office.com/webhook/stuffNthings
```
