### ISSUE TITLE
git: non-interactive clone using git protocol not working

### ISSUE THREAD

**Issue by mbana** [circleci/circleci-docs#2429]
When I attempt to clone a repo using `git://` I get this prompt. I do not have the passphrase, it looks like CircleCI set it up.

How does one do a non-interactive checkout using the `git://` protocol?

```sh
git clone --depth 1 git@github.com:org/repo.git)
...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Enter passphrase for key '/home/circleci/.ssh/id_rsa':
```

**Comment by smart-alek** [comment]
Hey @mbana! Thanks for filing an issue. Couple questions for you:

- Where are you running this command?
- Were you looking at a specific document when you ran into this problem?

**Comment by mbana** [comment]
```yaml
 - run:
      name: Avoid hosts unknown for github
      command: git clone git@github.com:org/repo.git
```

pick any public repo, it looks like it fails prompting me to enter in the passphrase.
