### ISSUE TITLE
Assignment of environment variables wrong documented

### ISSUE THREAD

**Issue by epandasa** [circleci/circleci-docs#2514]
# Locations
Add a link to the document
with the incorrect information.
[General Document: Environment Variables](https://circleci.com/docs/2.0/env-vars/)

## Passages: 
[Setting an environment variable in a container](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-container)
[Setting an environment variable in a step](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-step)
[Setting an environment variable in a job](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-job)

# Details
The right syntax should be an equal sign, at least this is what the build says if i run it, with the faulty configuration. 

![image](https://user-images.githubusercontent.com/13852415/43135666-7872c0d0-8f46-11e8-96cc-1116fc268e17.png)

Her is my config file, which i used for this build.
``` 
version: 2
jobs:
  docker-pre-flight:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run: 
          name: validate docker credentials and pull build container
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS          
  
  docker-pull-build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run: 
          name: pull dummy build container
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker pull dummy/build

  docker-pull-circleci:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run: 
          name: pull dummy circleci container
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker pull dummy/circleci

  docker-pull-dummy-ansible:
    docker:
        - image: docker:17.05.0-ce-git
    steps:
        - setup_remote_docker
        - run:
            name: pull dummy ansible container
            command: |
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                docker pull dummy/ansible

  build-default:
    working_directory: /app
    docker:
      - image: dummy/circleci
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
      - image: redis
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Restore the projects
          command: |
            npm install -g bower
            chmod u+x build.sh
            ./build.sh --no-publish --no-test # just restore
      - run: 
          name: build the artifacts 
          command: |
             chmod u+x build.sh
             ./build.sh --no-restore --docker-build --docker-push
      - run:
          name: signin to docker
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: 
          name: build backend container image
          command: |
            docker build -t dummy/backend:$CIRCLE_BUILD_NUM ./artifacts/dummy.Backend
      - run:
          name: build backoffice container image
          command: |
            docker build -t dummy/backoffice:$CIRCLE_BUILD_NUM ./artifacts/dummy.Backoffice
      - run: 
          name: build email container image
          command: |
            docker build -t dummy/email:$CIRCLE_BUILD_NUM ./artifacts/dummy.Email
      - run:
          name: build website container image
          command: |
            docker build -t dummy/website:$CIRCLE_BUILD_NUM ./artifacts/dummy.Website
      
      - run: 
          name: push container to registry
          command: |
            docker push dummy/backend:$CIRCLE_BUILD_NUM
            docker push dummy/backoffice:$CIRCLE_BUILD_NUM
            docker push dummy/email:$CIRCLE_BUILD_NUM
            docker push dummy/website:$CIRCLE_BUILD_NUM


  deploy-staging:
    docker:
      - image: dummy/circleci
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    working_directory: /app
    environment:
        REPO_PATH:/app
        AWS_SECRET_ACCESS_KEY:$AWS_SECRET_ACCESS_KEY
        AWS_ACCESS_KEY_ID:$AWS_ACCESS_KEY_ID
    steps:
      - setup_remote_docker
      - checkout
      - run: 
          name: generate aws config file
          command: |
            mkdir ~/.aws
            echo "[default]" >> ~/.aws/config
            echo "aws_access_key_id="$AWS_ACCESS_KEY_ID >> ~/.aws/config
            echo "aws_secret_access_key="$AWS_SECRET_ACCESS_KEY >> ~/.aws/config
            echo "region=eu-central-1" >> ~/.aws/config
            cat ~/.aws/config
      - run: 
          name: deploy staging 
          command: |            
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            chmod u+x deploy.sh
            chmod u+x deploymnet/run-playbook.sh
            ./deploy.sh staging

  
        
workflows:
  version: 2
  build-deploy:
    jobs:
      - hold:
          type: approval
      - docker-pre-flight
      - docker-pull-build:
          requires:
            - docker-pre-flight
      
      - docker-pull-dummy-ansible:
          requires:
            - docker-pre-flight
          filters:
            tags: 
              only: /^production-.*/
            branches:
                only:
                    - master
                    - development
          
      
      - docker-pull-circleci:
          requires: 
            - docker-pre-flight
            
      - build-default:
          requires:
            - docker-pull-circleci
            - docker-pull-build
  
      - deploy-production:
          requires:
            - hold
            - build-default
            - docker-pull-dummy-ansible
          filters:
            tags: 
              only: /^production-.*/
            branches:
              ignore: /.*/
  
      - deploy-staging:
          requires:
            - hold
            - build-default
            - docker-pull-dummy-ansible
          filters:
            branches:
              only: master
  
      - deploy-edge:
          requires:
            - hold
            - build-default
            - docker-pull-dummy-ansible
          filters:
            branches:
              only: development
```
