### ISSUE TITLE
Elixir caching

### ISSUE THREAD

**Issue by tielur** [circleci/circleci-docs#2535]
# Location
https://circleci.com/docs/2.0/language-elixir/

# Explanation
The sample configuration is restoring these caches for the build cache
```yaml
- restore_cache:  # restores saved build cache
    keys:
      - v1-build-cache-{{ .Branch }}
      - v1-build-cache
```

but it's saving these:
```yaml
- save_cache: # don't forget to save a *build* cache, too
    key: v1-mix-cache-{{ checksum "mix.lock" }}
    paths: "_build"
- save_cache: # don't forget to save a *build* cache, too
    key: v1-build-cache-{{ .Branch }}
    paths: "_build"
- save_cache: # and one more build cache for good measure
    key: v1-build-cache
    paths: "_build"
```

I'm not sure if the correct fix is to remove the `checksum` `save_cache` call or to add a `restore_cache` key for `v1-mix-cache-{{ checksum "mix.lock" }}`

**Comment by tielur** [comment]
@smart-alek Ahh ok so there are two separate calls to `save_cache` with the same `key` but because it's different paths ( one  for `_build` and one for `deps` ) they wont overwrite each other?

**Comment by tielur** [comment]
And if so, for consistently doesn't it make sense to combine that into one call but with multiple paths to avoid this confusion?

**Comment by smart-alek** [comment]
OH MY GOODNESS @tielur — I think you found a bug! Have a 🍪 .

Take a look at the [Real Configuration](https://github.com/CircleCI-Public/circleci-demo-elixir-phoenix/blob/master/.circleci/config.yml) for this project.

```yaml
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"
```

The weird inconsistency that threw you off is actually incorrect documentation, so shame on me for not carefully looking at the snippet you posted! 😬 I'll update the configuration sample in our docs posthaste. :)
