### ISSUE TITLE
Sauce labs sample commands not correct

### ISSUE THREAD

**Issue by gst-zhilun** [circleci/circleci-docs#2540]
# Locations
https://circleci.com/docs/2.0/browser-testing/#sauce-labs

# Details
Sample Code below is for Wrapper around the Sauce Labs REST API for Node.js then run a script called sauce.
```YAML
      - run: 
          name: Install Sauce
          command: npm install saucelabs
      - run: 
          name: sauce testing
          command: npm run-script sauce
          environment:
            SAUCE_USERNAME: # Refer to circleci.com/docs/2.0/env-vars documentation for info
            SAUCE_ACCESS_KEY: # about setting up environment variables for auth secrets
```
What we need is to download sauce connect and set up the secure tunnel. Below is partial code from @eddiewebb repo circleci-challenge config.yml and is what should be inside document. The link of that file is [this](https://github.com/eddiewebb/circleci-challenge/blob/master/.circleci/config.yml)
``` YAML
      - run:
          name: Start SauceLabs Tunnel (required if testing on CircleCI container)
          command: |
            curl https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
            cd sc-*
            # startup saucelabs tunnel as background task (its a blocking command)
            bin/sc -u ${SAUCELABS_USER} -k ${SAUCELABS_KEY} &
            #wait for sauce tunnel up to 1 minute
            wget --retry-connrefused --no-check-certificate -T 60 localhost:4445
```
Also similar code can be found in v1.0 document
