### ISSUE TITLE
[CircleCi 2.0] How to execute tests using parallelism?

### ISSUE THREAD

**Issue by ec-wagner** [circleci/circleci-docs#2705]
# Missing Information
From the documentation about "Running Tests in parallel" which I found here https://circleci.com/docs/2.0/parallelism-faster-jobs/ I understood how to split test files but I did not get how to execute the splited tests in a parallel way

I my case the run command to execute tests looks like this:
```bash
atest/run.py python3 atest/robot/<subfolder>
```
The `<subfolder>` contains `*.robot` files which hold the actual test cases.

### example
```yaml
- run:
      command: >
          python atest/run.py python --output NONE --report NONE --log NONE
          atest/robot/cli
```

How do I apply `circleci tests glob` or  `circleci tests split` to my execution command? In particular I don't get where to go from here 
```yaml
- run:
    command: |
        circleci tests glob atest/robot/cli/**/*.robot | circleci tests split
```
... or how to combine it with my execution command `atest/run.py python`

# Already Looked
https://circleci.com/docs/2.0/parallelism-faster-jobs/  and the youtube video which is provided there

# Potential Locations
https://circleci.com/docs/2.0/parallelism-faster-jobs/

## Tags
`python`
`robotframework`
`robot framework`
