### ISSUE TITLE
Bug in "Sharing CircleCI’s X Server"

### ISSUE THREAD

**Issue by eric-simonton-sama** [circleci/circleci-docs#2711]
# Description
The command listed to run `x11vnc` has a stray colon that causes it to fail.
```yml
steps:
  - run:
   name: Download and start X
   command: |
     sudo apt-get install -y x11vnc
     x11vnc -forever -nopw:         <----- the stray colon is here
   background: true
```

However, after removing the colon I'm still having trouble figuring out to how to make this work. It would be great if somebody would verify everything in this section of the documentation, in addition to removing the colon.

# Location
https://circleci.com/docs/2.0/browser-testing/#sharing-circlecis-x-server

# Steps to Reproduce
Simply use the command from the documentation in the circle config.
