### ISSUE TITLE
Setup Build Triggers in Docker Hub

### ISSUE THREAD

**Issue by bparanj** [circleci/circleci-docs#2934]
# Missing Information

Configuration for triggering a build in Docker hub. Docker Hub provides Trigger token and Trigger URL. 

# Already Looked

https://discuss.circleci.com/t/triggering-docker-hub-builds-from-circleci/7969/7

Looking for the version 2.0 format. Most of the resources are using the old format.

The old configuration looks like this:

```
deployment:
  dockerhub:
    branch: master
    commands:
      - $DOCKER_HUB_TRIGGER
```

The DOCKER_HUB_TRIGGER variable is set to the Trigger url provided by Docker Hub in the Circleci project settings.

# Potential Locations

How to Configure Circleci to Trigger Build in Docker Hub

**Comment by teesloane** [comment]
Hi @bparanj, thanks for opening this ticket.

Are you trying to trigger a remote build as specified in this [dockerhub document](https://docs.docker.com/docker-hub/builds/#remote-build-triggers)? If so, you could run a `curl` command from your config to trigger your build remotely:

```yaml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0-browsers # < an arbitrarily chosen docker image.
    steps:
      - checkout
      - run:
          # example curl request from dockerhub documentation
          name: Trigger docker remotely
          command: curl --data build=true -X POST https://registry.hub.docker.com/u/svendowideit/testhook/trigger/be579c82-7c0e-11e4-81c4-0242ac110020/
```

Otherwise, you might want to checkout the [building docker images](https://circleci.com/docs/2.0/building-docker-images/) doc. CircleCI 2.0 allows you to run `docker` commands on the machine executor, and the docker executor ( with the `setup_remote_docker` key), allowing you to build / push docker images as well.
