### ISSUE TITLE
Java OOM instructions are unclear

### ISSUE THREAD

**Issue by dwmkerr** [circleci/circleci-docs#2944]
# Missing Information

There is substantial documentation on the different environment variables available for Java memory usage. However, there is no suggested variable to use as a 'best choice' for projects.

# Already Looked

- https://circleci.com/docs/2.0/java-oom/
- https://circleci.com/blog/how-to-handle-java-oom-errors/

# Suggestion

I would suggest that we add more into the docs, such as:

**Android Projects**

In most cases, gradle build out-of-memory errors will be resolved with:

```
environment:
  JAVA_OPTS: "-Xms512m -Xmx1024m"
  _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
  GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
```

I think this would be really useful because I cannot actually find suggested settings anywhere and it's still totally hit and miss for me what might actually work!
