### ISSUE TITLE
Include information about how to install specific Node versions in CircleCI Docker images

### ISSUE THREAD

**Issue by li3n3** [circleci/circleci-docs#3049]
# Missing Information
A customer had an excellent suggestion while troubleshooting an nvm slowdown relative to iojs.org being down.

It would be great if the CircleCI documentation was updated to include instructions on how to install a specific version of Node in the various `<language>-node` images. There are many blog posts in this space, but we do not appear to have this information in our docs yet.

This is especially important as, at least for the Ruby images, the version of Node installed by default is 8.x, which is behind the current Node LTS release of 10.x.

# Already Looked
Searched in CircleCI docs, e.g. https://circleci.com/docs/?query=node%20version. Nothing appears relevant from the titles and snippets displayed.

# Potential Locations
_Tell us where you would expect to find this information.
This can be either an existing document,
or an entirely new document._
https://circleci.com/docs/2.0/circleci-images/#best-practices
or https://circleci.com/docs/2.0/faq/#what-is-the-best-practice-for-specifying-image-versions
could be options. It also might go best in a new document.

**Comment by michelle-luna** [comment]
Thanks @li3n3 ! Can you point to the blog posts please and we'll get it added.

**Comment by teesloane** [comment]
I was googling around for some solutions for this and stumbled on this [issue](https://github.com/circleci/circleci-images/issues/188). I'm not sure it's possible to use anything other than the LTS as @felicianotech mentioned in [this comment](https://github.com/circleci/circleci-images/issues/188#issuecomment-386888248)?

**Comment by felicianotech** [comment]
In the current state of convenience images, the Node Variant images are using the LTS release of Node.js. Right now, the images are using Node.js v10.

If someone wants to use a different version of Node, they need to install the version they want. They need to start at the Node.js [Downloads](https://nodejs.org/en/download/) page. The reason being, it's the same install instructions. Our images use different OSs, be it different versions of Debian or even Alpine. They'd need to follow the official Nodejs instructions for the OS they are using.

---

This process will be easier for our new upcoming images, but we don't have an ETA at the moment.

Right now the answer is, if you need to install a specific version of Node, install it. Perhaps, what we should mention in the Docs is how to remove the existing install? If that's even needed.

**Comment by teesloane** [comment]
Thanks for weighing in @felicianotech. Just to clarify — if a user wants to use a different version of node in their config, are they installing it within the custom CircleCI docker container, or are they going to be writing a custom docker file with the version of node they want to use?

**Comment by felicianotech** [comment]
They'd run the commands to install Node.js via a `run` step in the CircleCI config file.

**Comment by teesloane** [comment]
Ah, gotcha. Thank you for clarifying! I will add some docs as per requested in the best-practices section in the circle images doc.

**Comment by teesloane** [comment]
So, I've clarified the docs that we have, but I thought it would be good to include an example how to change your version of node in your config. I have something that is almost working (see below). In the config, I run a command to fetch NVM, set environment variables to recognize `nvm` commands, install a node verison, `use` it, and then try using the newly installed `node` version in future commands.

```
version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run:
          name: Setup dirs + env_vars for NVM installation.
          command: |
            mkdir $HOME/.nvm; echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
            echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
      - run:
          name: Check current version of node
          command: node -v
      - run:
          name: Get + install node version manager.
          command: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
      - run:
          name: Install a different version of node.
          command: nvm install 6.14.4
      - run:
          name: Indidcate which version of node to use.
          command: nvm use 6.14.4; node -v # < success: running `nvm use X.xx.x` followed by a node command in the same statement works.
      - run: node -v # << problem: successive `run`  commands don't use the newly set verison of node.
```

Right now, the last two lines represent where I'm stuck. I feel like maybe there is an easier approach? Maybe just use a package manager to download node into the container and overwrite the version that comes with the image?

**Comment by felicianotech** [comment]
Why nvm instead of installing Nodejs directly?

```
version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64    /bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: Check current version of node
          command: node -v
```

That would install Node.js v11.10 for example.
