### ISSUE TITLE
Building a PHP project yields a phpunit failure

### ISSUE THREAD

**Issue by makareth** [circleci/circleci-docs#3064]
# Description
I just setup a Symfony project using Linux / PHP, as suggested by CircleCI. I used the typical config.yml provided by CircleCI when setting up the project : 
```
# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: phpunit

```
When building, the Spin up Environment, Checkout Code, Restoing Cache, composer install and Saving cache operations are OK, bu the phpunit operation fails : 

```
#!/bin/bash -eo pipefail
phpunit
/bin/bash: phpunit: command not found
Exited with code 127
```

# Steps to Reproduce
1/ Create a typical Symfony project (PHP) on github
2/ Add the Github project to CircleCI
3/ Copy-Paste the config.yml provided by CircleCI for a Linux/PHP project.
4/ Click the Build button.
