### ISSUE TITLE
Parallel workflow

### ISSUE THREAD

**Issue by xyluet** [circleci/circleci-docs#3137]
# Description
It not run in parallel. For example I want test and lint run together without waiting one another.

# Expected
lint and test run without waiting one another.

# Actual
it random, it will wait lint or test to finish first. But sometimes it work.

# Steps to Reproduce
```yml
version: 2.0

jobs:
  lint:
    docker:
      - image: circleci/node:8.10
    steps:
      - run: sleep 10 && echo 1

  test:
    docker:
      - image: circleci/node:8.10
    steps:
      - run: sleep 10 && echo 1

workflows:
  version: 2
  master:
    jobs:
      - lint
      - test

```
