### ISSUE TITLE
Example code is duplicated in 'reusing-config.md'

### ISSUE THREAD

**Issue by WasWere** [circleci/circleci-docs#3192]
# Location

https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/reusing-config.md
https://github.com/circleci/circleci-docs/commit/3f01d62abc518e5bc5bebd1a3160d7c32a088571

# Explanation
The above commit appears to duplicate existing information.
The code example for 'Authoring Reusable Executors' appears twice in the current version, but didn't before the 13th of February.

Changes in this commit should be reverted.

### Quote
#
In the following example `my-executor` is passed as the single value of the key `executor`. 

 ```yaml
version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
 jobs:
  my-job:
    executor: my-executor
    steps:
      - run: echo outside the executor
```

```yaml
version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
 jobs:
  my-job:
    executor: my-executor
    steps:
      - run: echo outside the executor
```
	
**Note:** Reusable `executor` declarations are available in configuration version 2.1 and later.

#
