### ISSUE TITLE
RE: jekyll/_docs/docker.md

### ISSUE THREAD

**Issue by pkyeck** [circleci/circleci-docs#322]
I'm trying to get "Caching Docker layers" to work, but your system always redownloads the node:4.5 image.

Here is my `circle.yml` - may you see a mistake I did :(

``` yaml
machine:
  services:
    - docker

dependencies:
  cache_directories:
    - "~/docker"

  override:
    - docker info
    - ls -lisa ~/docker/
    - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
    - docker build -t myimage .
    - mkdir -p ~/docker; docker save myimage > ~/docker/image.tar

test:
  override:
    - docker run myimage /bin/bash -c "npm test --loglevel warn"
```

As you can see, I output the content of the `~/docker` folder and the `image.tar` is theres ....!?
Is this still the way to go when trying to cache images/layers?
