### ISSUE TITLE
Missing example under reusing-config

### ISSUE THREAD

**Issue by jrr** [circleci/circleci-docs#3315]
# Locations
In the _Defining Conditional Steps_ Example at the bottom of the [reusing-config page](https://circleci.com/docs/2.0/reusing-config/#example).

# Conflict Description
The documentation refers to _two_ examples:
> The value is provided by the value true or false using parameters (first example), or by the result of a Bash function (second example).

But as far as I can tell, there's only one example, and no sign of a Bash function.

**Comment by montanaflynn** [comment]
I was also going to submit this. 

Really hoping circleci allows bash equality checks on environment variables in the condition but I couldn't find any examples.

Something like this would be ideal for me:

```
      - run:
        - when:
          condition: [ "$CIRCLE_BRANCH" == "master" ]
          steps:
            - run:
               name: Deploying master
               command: ./deploy.sh
```
