### ISSUE TITLE
RE: jekyll/_docs/language-python.md

### ISSUE THREAD

**Issue by Regner** [circleci/circleci-docs#340]
The docs mention that if a tox.ini file is found Circle CI will automatically run tox. However even if I have specified this:

```
machine:
  services:
    - docker
  post:
    - pyenv global 3.5.0
```

It fails to execute tox as tox is not installed.
