### ISSUE TITLE
Conditional conjunctions for when/unless

### ISSUE THREAD

**Issue by tklarryonline** [circleci/circleci-docs#3415]
# Location
https://circleci.com/docs/2.0/reusing-config/#defining-conditional-steps

# Explanation
It's not clear to me and my team whether or not we can use conjunctions in the `when`/`unless` clause. It seemed to us that we can't, though. We were able to use a single boolean parameter to do the trick, but are still interested in how we can actually achieve this of combining multiple parameters through conjunctions.

## Sample/snippet
Our sample below:

```yml
parameters:
  full_build:
    type: boolean
    default: true
  functional_tests:
    type: boolean
    default: false

steps:
  - when:
    condition: <<parameters.full_build>> or <<parameters.functional_tests>>
    steps:
      - run:
        name: foo

  - unless:
    condition: <<parameters.full_build>> or <<parameters.functional_tests>>
    steps:
      - run:
        name: bar

workflows:
  version: 2.1

  build_then_analysis:
    jobs:
      - build:
          name: Quick Tests
          full_build: false
```

When we run the "Quick Tests" job, it always runs the `foo` steps but not the `bar` steps above.

## What we have tried

We tried &, |, &&, ||, as well as the [simple logics in YAML](https://metacpan.org/pod/YAML::Logic) but couldn't make it work as we expected. We ended up using another boolean called `quick_test` to do the trick.
