### ISSUE TITLE
Failing Example: Sample Configuration with Imported Orb

### ISSUE THREAD

**Issue by egyptianbman** [circleci/circleci-docs#3528]
# Locations
https://circleci.com/docs/2.0/jobs-steps/#sample-configuration-with-imported-orb

# Details
Attempting to run a job similar to the first example, you'd likely get an error along the lines of:
```
#!/bin/sh -eo pipefail
# Error calling workflow: 'build-test-deploy'
# Cannot find a definition for job named deploy2s3
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false

Exited with code 1
```

**Comment by teesloane** [comment]
Hi there @egyptianbman -- so the code snippet linked isn't a full configuration reference; it's missing the `jobs` stanza. If you take a look at the [reusing config](https://circleci.com/docs/2.0/reusing-config/#using-the-parameters-declaration) document, you'll notice there are a few other partial examples; that one linked has a `jobs` stanza as you would need to better fill out your config. Hope that clears things up!

**Comment by egyptianbman** [comment]
'm accustomed to seeing an indication that something is a subset of a larger whole by utilization of `...`.

i.e.:
```yaml
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.0 #imports the s3 orb in the circleci namespace

jobs:
  deploy2s3:
     ...

workflows:
  build-test-deploy:
    jobs:
      - deploy2s3:
          steps:
            - aws-s3/sync: #invokes the sync command declared in the s3 orb
                from: .
                to: "s3://mybucket_uri"
                overwrite: true
```

This would clearly indicate that `deploy2s3` is referencing the jobs stanza. I was eventually able to track down the problem and moved on; thanks!
