### ISSUE TITLE
Python tests not being split among containers

### ISSUE THREAD

**Issue by wycio** [circleci/circleci-docs#3656]
I've integration tests that run inside Circle CI. These are running fine. But now I want to take advantage of parallelism so that tests could be run faster.

I read this https://circleci.com/docs/2.0/parallelism-faster-jobs/ and made changes to my `config.yml`. 

The problem I'm facing is that tests are not being split among containers. Every container seems to be running the same set of tests as if tests are being run without parallelism. 

I tried this command locally `circleci tests glob "tests/**/test_*.py"` and I see the correct split. But apparently, CircleCi isn't splitting tests among containers. 

Here is my config file, all help is appreciated:
```
version: 2 # use CircleCI 2.0
jobs: # A basic unit of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    # directory where steps are run
    working_directory: ~/blackbox_tests
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4
    parallelism: 4
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            mkdir test-reports
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          command: |
            . venv/bin/activate
            python -m pytest --junitxml=test-reports/junit.xml
            python -m pytest $(circleci tests glob "tests/**/test_*.py" | circleci tests split)
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1
```

**Comment by teesloane** [comment]
Before digging into possible problems, can you confirm whether or not you have a paid plan? Parallelization requires running across multiple containers; on our free plan we can only support running one concurrent job with one container at one x parallelism.

**Comment by wycio** [comment]
Hey @teesloane, thank you for your reply. 

Yes, we have a paid plan.

**Comment by teesloane** [comment]
hmm. In that case I'll try and re-create the issue and figure this out. Wish me luck! In the meantime, searching our [discuss forum](https://discuss.circleci.com/) might be of some use. 

Your glob for testing seems to be correct, but you could also try passing in a [file with a list](https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-by-name) of names to test as well. Sorry about this!

**Comment by teesloane** [comment]
Hi there—did you have any luck with splitting your tests? 

I tried working replicating your issue with a similar config )twirl the arrow down to view the config — it's pretty much the same as yours, though):

<details>

```yml
version: 2 # use CircleCI 2.0
jobs: # A basic unit of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    # directory where steps are run
    # working_directory: ~/blackbox_tests
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4
    parallelism: 4
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            mkdir test-reports
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          command: |
            . venv/bin/activate
            python -m pytest --junitxml=test-reports/junit.xml
            python -m pytest $(circleci tests glob "tests/**/test_*.py" | circleci tests split)
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1
```

</details>

---

When my build runs I see several containers running for the tests as in these screenshots. Mind you, I only have two dummy tests, both that sleep for a few seconds each.

<img width="1141" alt="Screen Shot 2019-08-22 at 2 35 34 PM" src="https://user-images.githubusercontent.com/12987958/63541070-58f01b00-c4eb-11e9-828b-360544055a99.png">
<img width="1355" alt="Screen Shot 2019-08-22 at 2 35 12 PM" src="https://user-images.githubusercontent.com/12987958/63541072-5988b180-c4eb-11e9-845e-ce2149662553.png">

Do you see something akin to this, or does each container literally just display the exact same tests?
