### ISSUE TITLE
python image not found

### ISSUE THREAD

**Issue by davidmoshal** [circleci/circleci-docs#3668]
# Description
```
Starting container python:3.6.0-jessie
  image cache not found on this host, downloading python:3.6.0-jessie

Error response from daemon: manifest for python:3.6.0-jessie not found
```

# Location
https://circleci.com/docs/2.0/artifacts/#section=jobs

# Steps to Reproduce
run this example:
```yml
version: 2
jobs:
  build:
    docker:
      - image: python:3.6.0-jessie

    working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
```
