### ISSUE TITLE
Outdated instruction on how to use orbs

### ISSUE THREAD

**Issue by phuongnd08** [circleci/circleci-docs#3693]
# Locations
https://circleci.com/docs/2.0/ecs-ecr/#prerequisites
# Details

I have this inside my .circleci/config.yml
```
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2

workflows:
  version: 2
  build_and_test:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
          dockerfile: Dockerfile.development
          extra-build-args: "--build-arg BUNDLE_GITHUB__COM=cc585d60d77bfb75e5fe7dfcad55da223b37abec"
      - bundle_install:
          requires:
            - aws-ecr/build_and_push_image


```

And this is circle telling me:

```
We weren't able to start this workflow.
Encountered errors trying to create workflows from this config: Config does not conform to schema: {:workflows {:build_and_test {:jobs [{:aws-ecr/build_and_push_image {:account-url disallowed-key, :repo disallowed-key, :region disallowed-key, :tag disallowed-key, :dockerfile disallowed-key, :extra-build-args disallowed-key}} nil nil nil nil nil nil nil]}}}
For more examples see the Workflows documentation.
```
