### ISSUE TITLE
Cannot recognize js imports

### ISSUE THREAD

**Issue by CristianoYL** [circleci/circleci-docs#3817]
# Description
For a basic react app (created by **CRA**), the CircleCI job would fail on this line of import:

```
import App from './app';
```

# Steps to Reproduce
 1. Generate a React App with CRA.
 1. Rearrange the App* files into a new folder in `/src` with 3 files. e.g:
```
src/components/App
               |____app.js
               |____index.js
               |____app.test.js

```
the `index.js` would export **App** from `app.js` like so:
```
import App from "./app";
 
export default App;
```
1.  run the tests locally (passed)
1.  run on CircleCI (failed)

error output:
```
yarn run v1.19.0
$ react-scripts test
 FAIL  src/components/App/app.test.js
  ● Test suite failed to run

    Cannot find module './app' from 'index.js'

    However, Jest was able to find:
    	'./app.test.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

    > 1 | import App from "./app";
        | ^
      2 | 
      3 | export default App;
      4 | 

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (src/components/App/index.js:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.278s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

It seems that somehow it doesn't recognize the './app' in **src/components/App/index.js** refers to `./app.js`.
Note that the default 'moduleFileExtensions' config does contain `js` as pointed out in the error log.

I'm sure it should be a simple fix, but couldn't figure it out. I've tried with different node images and had the same issue. Everything works locally though. 

BTW, here's the `config.yml`:

```
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
```

Thanks in advance.
