### ISSUE TITLE
Error in documentation about using-when-in-workflows

### ISSUE THREAD

**Issue by testautomation** [circleci/circleci-docs#3905]
# Location
https://circleci.com/docs/2.0/configuration-reference/#using-when-in-workflows

# Details
![image](https://user-images.githubusercontent.com/38438046/68354941-039cd080-010e-11ea-8ff3-6351ab3dbf15.png)

I took your example and run `circleci config validate` over it and got this error:
```
$ circleci config validate
Error: Error calling workflow: 'integration_tests'
Cannot find a definition for job named when
```

**Comment by rosieyohannan** [comment]
Hi @testautomation thanks so much for reporting this... I just ran the same steps but am not getting this error. Can I just check, did you copy and paste the example straight from docs? Just wondering if maybe you have an incorrect indentation somewhere in the YAML? I believe the usage of `when` is correct in the example, but would like to help get to the bottom of the issue you're seeing.

**Comment by testautomation** [comment]
Hi @rosieyohannan 

> Can I just check, did you copy and paste the example straight from docs?
yep, just copied and added a simple job named `mytestjob` below `jobs:`

here it is:
```yaml
version: 2.1

parameters:
  run_integration_tests:
    type: boolean
    default: false
  deploy:
    type: boolean
    default: false

workflows:
  version: 2
  integration_tests:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
      - mytestjob
      - when:
          condition: << pipeline.parameters.deploy >>
          steps:
            - deploy

jobs:
  mytestjob:
    machine: ubuntu
    steps:
      - run: echo world
```

**Comment by testautomation** [comment]
```
$ circleci version
0.1.5879+416032d
```

**Comment by rosieyohannan** [comment]
Thanks 👍 ... 👀

**Comment by rosieyohannan** [comment]
Hi again - so it seems that the section using `when` to determine if an individual workflow step should run is not correct within the `workflows` section. This would have to be done within the `job` definition. Within `workflows`, `when` can be used with the first usage shown, to determine whether the whole workflow should run. I'm going to update docs to reflect this. Sorry for all the confusion!

```
version: 2.1

parameters:
  run_integration_tests:
    type: boolean
    default: false
  deploy:
    type: boolean
    default: false

workflows:
  version: 2
  integration_tests:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
      - mytestjob

jobs:
  mytestjob:
    machine: ubuntu
    steps:
      - run: echo world
```

**Comment by testautomation** [comment]
Thank you for clarification! 

❤️

**Comment by testautomation** [comment]
btw. I would be great to have examples of how to use the parameter 
```
<< pipeline.parameters.run_integration_tests >>
```

For example I would like to have something like

```yaml
parameters:
  finished-tests:
    type: integer
    default: 0
```

Inside of several test execution jobs (which may run in parallel) I would like to update `finished-tests` parameter at the end of each job. Then in a conditional workflow I would like to define something like
> **if `finished-tests == 5`**

trigger this workflow. 

I have an example of concrete use case here: 
https://gist.github.com/testautomation/c7899c234657469ef0ebf2f14f92095f
