### ISSUE TITLE
Caching strategies for monorepos (Lerna, Yarn workspaces)

### ISSUE THREAD

**Issue by mattmazzola** [circleci/circleci-docs#3933]
# Missing Information
I was looking for caching techniques for monorepos and didn't see any.

I was in process of converting from bunch of regular single package repos which can use the suggested cache key of `v1-npm-deps-{{ checksum "package-lock.json" }}`; however, for monorepos where there are multiple / nested `package.json`s this does not suffice.

The outer package wouldn't capture changes to inner packages.

The solution I came up with was to simply concatenate checksums of multiple package jsons such as:
`v1-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "./packages/models/package.json" }}-{{ checksum "./packages/sdk/package.json" }}-{{ checksum "./packages/ui/package.json" }}-{{ checksum "./packages/samples/package.json" }}`

Example:
`v1-deps-master-G+CP6jVyNkkNpKOWJ4mGVti55LeiwFsAuK3KvWJM5hs=-ae0DuAPUQBWmNGYWamxK282FaJoc_TEFiGp+alY_W2c=-nM+E_1mrETTdBUc63QmS+RM_U6tTssoCjrvSC6Xo9jk=-81coRH8sTogaOf351TSoxPKMoaeUMfm26ID9PQHOjqo=-ya0WvUSus9OaXzcjK1pYuf6NDQUpNlpjij2GrBNoH08=`

However, this doesn't scale well as it would require manual modification everytime a package was added.  I think there would a way to programmatically generate a key string based on package.json's in the repo but that would be more complicated.

# Already Looked
https://circleci.com/docs/2.0/caching/#restoring-cache

# Potential Locations
https://circleci.com/docs/2.0/caching/#restoring-cache

I expect it to be found on this page. I understand my use case is more rare than traditional but it wouldn't hurt to add it as a small section at the bottom which could be linked too.

**Comment by glenjamin** [comment]
Hi Matt

I would personally recommend having one cache per set of packages, so each can change independently.

If you have different jobs that operate on different parts of the monorepo, then you also benefit by not having to download the dependencies from other parts.

I also don't recommend including `Branch` in the key, as when you're checksumming a lockfile branches are more likely to match already.

I'll often handle this by creating a [re-usable command](https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-commands) a bit like this.

```
commands:
  npm-ci:
    parameters:
      path:
        type: string
    steps:
      - restore_cache:
          keys:
            - v1-npm-<< parameters.path >>-{{ checksum "<< parameters.path >>/package-lock.json" }}
            - v1-npm-<< parameters.path >>-
      - run:
          command: npm ci
          working_directory: << parameters.path >>
      - save_cache:
          paths: << parameters.path >>
          key: v1-npm-<< parameters.path >>-{{ checksum "<< parameters.path >>/package-lock.json" }}
```

I've just written that out in the comment, so it hasn't been tested - but that should set you off in the right direction.

**Comment by mattmazzola** [comment]
Ok,

If I understand your example correctly it would work like this:
```
- npm-ci:
  - path: ./packages/models
- npm-ci:
  - path: ./packages/ui
- npm-ci:
  - path: ./packages/sdk
- npm-ci:
  - path: ./packages/samples
```

It seems like this would work, but I'm not sure I'm not sure how to measure caching improvements. It also has some downsides that maybe I didn't make clear.

### 1. Replicate the build process a developer would do on local machine.
We are using `lerna` and want to keep a standard build process on the builds. This means running `lerna bootstrap` (which simulates running `npm ci` in the packages)

### 2. Caching
We use the npm cache path (https://docs.npmjs.com/cli/cache#cache)
Which is  `~/.npm` path instead of entire package folder `./packages/modes` as your command would produce.

If it helps our current builds look like this (I did remove the `.Branch` part of the cache key so branches with no packages changes will still match the key
```
      - restore_cache:
          keys:
            - v3-deps-{{ checksum "package-lock.json" }}-{{ checksum "./packages/models/package-lock.json" }}-{{ checksum "./packages/sdk/package-lock.json" }}-{{ checksum "./packages/ui/package-lock.json" }}-{{ checksum "./packages/samples/package-lock.json" }}
            - v3-deps

      - run: node --version
      - run: npm --version
      - run: npx lerna bootstrap

      - save_cache:
          key: v3-deps-{{ checksum "package-lock.json" }}-{{ checksum "./packages/models/package-lock.json" }}-{{ checksum "./packages/sdk/package-lock.json" }}-{{ checksum "./packages/ui/package-lock.json" }}-{{ checksum "./packages/samples/package.json" }}
          paths:
            - ~/.npm
            - ~/.cache

      - run: npx lerna run build
      - run: npx lerna run test
```

**Comment by glenjamin** [comment]
ah I see, because some subfolders will use the same packages, then having the shared cache is useful.

I thinnk your best here would be to get lerna to print out a list of the lock files, and then cat them all together into a single file in an earlier step - then use that in the cache key.

**Comment by thomasr8** [comment]
@glenjamin Do you think this should be added in our documentation?

**Comment by mattmazzola** [comment]
Adding my solution here if you want to based the docs on it:

1. Add custom command to config:
```
commands:
  create_concatenated_package_lock:
    description: "Concatenate all package-lock.json files recognized by lerna.js into single file. File is used as checksum source for part of caching key."
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Combine package-lock.json files to single file
          command: npx lerna list -p -a | awk -F packages '{printf "\"packages%s/package-lock.json\" ", $2}' | xargs cat > << parameters.filename >>
```

2: Use custom command in build to generate the concatenated package-lock file
```
    steps:
      - checkout
      - create_concatenated_package_lock:
          filename: combined-package-lock.txt
```

3. Use `combined-package-lock.text` in cache key
```
      - restore_cache:
          keys:
            - v3-deps-{{ checksum "package-lock.json" }}-{{ checksum "combined-package-lock.txt" }}
            - v3-deps
```

**Comment by glenjamin** [comment]
> @glenjamin Do you think this should be added in our documentation?

Yeo, the more monorepo tips we can include in the docs, the better!

**Comment by evantahler** [comment]
Great idea! 

Expanding on this a little more generally, I've just used `find` to find the lockfiles in my lerna repo (we've got `plugins`, `apps`, and some other things)

```bash
#!/bin/bash

# This command is for Circle CI to have one place to build a cache checksum from
# We concat all the package-lock.json files in the project into one big file.

set -e

PROJECT_ROOT=$(cd $(dirname $0)/.. && pwd)
FILES=`find $PROJECT_ROOT -name package-lock.json | grep -v node_modules`
OUTPUT="$PROJECT_ROOT/combined-package-lock"

# printf "$FILES"

rm -rf $OUTPUT

for p in $FILES ; do
  echo "----- $p -----" >> $OUTPUT
  cat $p >> $OUTPUT
  printf "  added $p\r\n"
done

printf "\r\ndone!\r\n"
```

**Comment by mattmazzola** [comment]
Yea, think there would be many ways to get the paths to the files. I could see people prefering this as more readable than having to understand the `awk` command. I had a co-worker help with with the flags and syntax as I wasn't familiar with it myself.

That being said, after we had this solution working for `npm` I saw `yarn` workspaces only produces a single top level lockfile.

> Yarn will use a single lockfile rather than a different one for each project, which means fewer conflicts and easier reviews.

https://classic.yarnpkg.com/en/docs/workspaces#toc-why-would-you-want-to-do-this

With NPM@7 suppose to release soon with their workspaces / multi-package support we should see if they have similar options which make these solution obsolete.

**Comment by airtonix** [comment]
I don't know why every tutorial out there recommends basing your cache strategy on `package.json`... :roll_eyes: 

- changing the task commands: cache invalidated
- while i think it's dumb, changing some tooling configuration stored in `package.json`: cache invalidated

@mattmazzola is correct, your cache invalidation should be based on the package managers lock file.

anyway, this is our yarn install command:

```
---
description: |
  Perform a yarn install with caching.

parameters:

  cache_version:
    type: integer
    default: 300

  install_command:
    type: string
    default: ""

  working_directory:
    type: string
    default: "."

  cache_directory:
    type: string
    default: "~/.cache/yarn"

steps:

  - run:
      name: Create cache checksum file
      command: |
        mkdir -p ~/.tmp/checksumfiles
        find . -type f -name 'yarn.lock' -not -path "*node_modules*" -exec cat {} + >> ~/.tmp/checksumfiles/yarn.lock

  - restore_cache:
      keys:
        - yarn-cache-<< parameters.cache_version >>-{{ arch }}-{{ checksum "~/.tmp/checksumfiles/yarn.lock" }}
        - yarn-cache-<< parameters.cache_version >>-{{ arch }}
        - yarn-cache-<< parameters.cache_version >>

  - when:
      condition: <<parameters.install_command>>
      steps:
        - run:
            name: Install Node Modules (custom)
            command: <<parameters.install_command>>
            no_output_timeout: 1h

  - when:
      condition:
        not: <<parameters.install_command>>
      steps:
        - run:
            name: Install Node Modules
            working_directory: <<parameters.working_directory>>
            command: >-
              yarn install
              --frozen-lockfile
              --cache-folder <<parameters.cache_directory>>
            no_output_timeout: 1h

  - save_cache:
      paths:
        - <<parameters.cache_directory>>
      key: yarn-cache-<< parameters.cache_version >>-{{ arch }}-{{ checksum "~/.tmp/checksumfiles/yarn.lock" }}

```

**Comment by lf-hernandez** [comment]
Are there any issues with just relying on the combined lock file solely?

e.g.
```yaml
- restore_cache:
    keys:
         - v3-deps-{{ checksum "combined-package-lock.txt" }}
         - v3-deps
- save_cache:
    key: v3-deps-{{ checksum "combined-package-lock.txt" }}
```

Would the prepended package-lock entry (`- v3-deps-{{ checksum "package-lock" }}-{{ checksum "combined-package-lock.txt" }}` be contained in the combined-package-lock? Assuming the combine lock file is saved in favor of the pacakges lock file.

**Comment by abhisheksr01** [comment]
Hi @mattmazzola ,

Thanks for your solution to this problem.

We are trying to implement the dependency cache mechanism with lerna as below:

**Note: None of our packages have packaga-lock.json files in our repo due to some existing issues hence our key is based on package.json**

```
commands:
  create_concatenated_package_json:
    description: "Concatenate all package.json files recognized by lerna.js into single file. File is used as checksum source for part of caching key."
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Combine package.json files to single file
          command: lerna la -a | awk -F packages '{printf "\"packages%s/package.json\" ", $2}' | xargs cat > << parameters.filename >>

JOB_NAME:
 - create_concatenated_package_json:
          filename: combined-package-json.txt
 - restore_cache:
         keys:
            - v2-deps-{{ checksum "package.json" }}-{{ checksum "combined-package-json.txt" }}


 - save_cache:
          key: v2-deps-{{ checksum "package.json" }}-{{ checksum "combined-package-json.txt" }}
          paths:
            - ./node_modules/
            - ./package-lock.json
            - ./packages/sub_package1/node_modules/
            - ./packages/sub_package1/package-lock.json
            - ./packages/sub_package2/node_modules/
            - ./packages/sub_package2/package-lock.json
            - .....

```

The cache gets uploaded and restored successfully, but we cannot see a noticeable improvement in the performance, which suggests the node is referring to the locally cached dependency rather than pulling from the internet.

We have compared the logs of our pipeline execution without and with cache enabled and didn't observe any difference.

Initially, we suspected it might be due to a missing packaga-lock.json file which causes npm to force install the dependencies but after adding them as well we didn't see an Improvement.

So do you have any suggestion on how we can ensure that when lerna commands are executed it won't pull the dependencies from the internet and pull from the cache?

Do you have
