### ISSUE TITLE
Filtering branch prevents being triggered for Pull Requests

### ISSUE THREAD

**Issue by nuhkoca** [circleci/circleci-docs#3934]
# Description
I am performing filtering to trigger my CircleCI on a certain branch. However, when I create a Pull Request for that branch, CircleCI is not triggered. IMHO, it should have been triggered even I create a PR on a specific branch.

# Steps to Reproduce

1. Add below block in config.yml

```
workflows:
  version: 2

  build_and_test:
    jobs:
      - build_and_setup:
          filters:
            branches:
              only: master
```

2.  Create a PR from another branch.
