### ISSUE TITLE
Manual triggers matryoshka dolls

### ISSUE THREAD

**Issue by phara0hcom** [circleci/circleci-docs#3959]
# Location
https://circleci.com/docs/2.0/triggers/

# Explanation
This is in the docs:
```
workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - test1
      - hold:
          type: approval # requires that an in-app button be clicked by an appropriate member of the project to continue.
          requires:
           - test2
      - deploy:
          requires:
            - hold
```

But there is no explanation why 
`hold` requires `test2` >> open  Big doll
`test2` requires `test1` >> open  medium doll
`test1` requires `build` >> open  small doll to find the build

Why not have this:
`hold` requires `build` Or is there a reason we need to do it this way?
