### ISSUE TITLE
Update inaccurate instructions (_cci1/installing-elasticsearch.md)

### ISSUE THREAD

**Issue by geraldke** [circleci/circleci-docs#397]
I followed the instructions on https://circleci.com/docs/installing-elasticsearch/

I have this on my circle.yml file to install ElasticSearch 2.3.3

```
dependencies:
  post:
    - wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-2.3.3.tar.gz
    - tar -xvf elasticsearch-2.3.3.tar.gz
    - elasticsearch-2.3.3/bin/elasticsearch: {background: true}
    - sleep 10 && curl --retry 10 --retry-delay 5 -v http://127.0.0.1:9200/
```

However, I'm getting intermittent errors on CircleCI on the curl step:

```
sleep 10 && curl --retry 10 --retry-delay 5 -v http://127.0.0.1:9200/
* About to connect() to 127.0.0.1 port 9200 (#0)
*   Trying 127.0.0.1... Connection refused
* couldn't connect to host
* Closing connection #0
curl: (7) couldn't connect to host

sleep 10 && curl --retry 10 --retry-delay 5 -v http://127.0.0.1:9200/ returned exit code 7

Action failed: sleep 10 && curl --retry 10 --retry-delay 5 -v http://127.0.0.1:9200/
```

Any suggestions?
