### ISSUE TITLE
When will CircleCi provide Docker for Windows?

### ISSUE THREAD

**Issue by khtan** [circleci/circleci-docs#4076]
# Missing Information
The section on Windows executor in https://circleci.com/docs/2.0/hello-world-windows/ explains that CircleCI provides Windows VM for building and testing. 

Windows 10/Windows Server 2016 supports running both Docker Linux and Docker Windows containers.

It would be good to mention whether/when CircleCI plans to add Docker for Windows as another Windows executor.

This will make it simpler for organizations with products on both Linux and Windows to standardize on Docker for
CICD.

What is CircleCI's plan to add Docker for Windows in their offerings? Or is this technology still
too new to be reliable for CircleCI's purposes.

# Already Looked
Provide a list of places you've already looked for this information.
Links are much appreciated.
documentation site: https://circleci.com/docs/
forum site: https://discuss.circleci.com/
http://google.com

# Potential Locations
Tell us where you would expect to find this information.
This can be either an existing document,
or an entirely new document.
https://circleci.com/docs/2.0/hello-world-windows/

**Comment by teesloane** [comment]
Hi there @khtan ,

I spoke with an engineer on this matter, and in response to your original issue, I learned that :

> Docker for windows (for windows containers) is already present. For example:

<details>
<summary> An example snippet of a config.yml that uses docker on windows</summary>

```yaml
    parameters:
      exec:
        type: executor
        default: win/default
    parallelism: 2
    working_directory: c:\\cache
    steps:
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            docker info
            docker run hello-world:nanoserver-1809
```
</details>

and that there are currently technical constraints that regarding enabling linux containers _on_ windows.

Are you referring to either of these situations, or something else ?
