### ISSUE TITLE
Permissions needed when using ECR for providing images

### ISSUE THREAD

**Issue by gms8994** [circleci/circleci-docs#4165]
# Missing Information
There's documentation about _how_ to use ECR within CircleCi, but there doesn't seem to be a list of the permissions required. Please note - I don't want to push images to ECR; only the ability to use them within CircleCi for running my tests.

# Already Looked
I couldn't find any information about permissions required to use an image provided by ECR.

# Potential Locations
https://circleci.com/docs/2.0/private-images/

**Comment by gms8994** [comment]
@thomasr8 may I ask why this issue was closed?

**Comment by thomasr8** [comment]
Hi

**Comment by thomasr8** [comment]
Hi @gms8994 Sorry about that; I mistakenly closed this issue earlier today. I have reached out to the Engineering team, and currently, there are no resources or bandwidth available to address this issue. I will keep this issue open to see if we can get some resources next month.

**Comment by seanmorris** [comment]
@gms8994 its been a while since I set it up but I have multiple images getting pulled & pushed to ECR on every build. I think you just need to set up the `AWS_KEY`, `AWS_SECRET`, and `AWS_REGION` environment variables in the project and set up a command like so:

```yml
version: 2.1

commands:
  auth:
    steps:
      - run: aws configure set aws_access_key_id "${AWS_KEY}"
      - run: aws configure set aws_secret_access_key "${AWS_SECRET}"
      - run: aws configure set region ${AWS_REGION}
      - run: aws ecr get-login | sed 's/-e none//'
```

My jobs all start like so:

```yml
jobs:
  build-test-push-web:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - auth
```
