### ISSUE TITLE
Step and processes (isolation between steps, backgound command)

### ISSUE THREAD

**Issue by jmini** [circleci/circleci-docs#4208]
# Missing Information

As far as I have tried, when you start a process during one step, it is no longer available in the next steps. See the first example of [my blog post](https://j2r2b.github.io/2020/03/05/circleci-step-isolation.html#the-circleci-step-isolation) that show the non working setup:
* a server is started in a non-blocking way during one step
* a `curl` command to query this server is executed in the next step.

And I get:
```
#!/bin/bash -eo pipefail
curl --request PUT "http://localhost:1080/mockserver/reset"

curl: (7) Failed to connect to localhost port 1080: Connection refused

Exited with code exit status 7

CircleCI received exit code 7
```

This is probably a consequence of what you wrote here:

> Each `run` declaration represents a new shell.

But it is not clear enough.

When I merge the 2 steps into a single one (start server and run `curl`) it works. This is my first solution.

----

Also not really documented: 

The idea of [background commands](https://circleci.com/docs/2.0/configuration-reference/#background-commands) (when the step is defined with `background: true`), is to start a process that is blocking and that is never ending.

This is proposed as second solution in my blog post:
https://j2r2b.github.io/2020/03/05/circleci-step-isolation.html#circleci-background-steps

----

Those two points are really logic and work as expected, when you have tried enough and tried to understand.

I hope my explanations are correct.

If you agree, I think that my findings (really specific in my blog post) could be written in a generic way in the official documentation.

# Already Looked
Provide a list of places you've already looked for this information.

* [Steps - configuration reference](https://circleci.com/docs/2.0/configuration-reference/#steps) and also the first section ("Run")
* [background commands](https://circleci.com/docs/2.0/configuration-reference/#background-commands)

Users are also asking on the forum and it is really easy to find those unanswered post if you search for "CircleCI curl connection refused" on Google. I could spot at least:

* [Can reach localhost using curl either inside or outside docker container](https://discuss.circleci.com/t/can-reach-localhost-using-curl-either-inside-or-outside-docker-container/15967)
* [Cannot curl to localhost: connection refused](https://discuss.circleci.com/t/cannot-curl-to-localhost-connection-refused/17885)
* ...

**Comment by rosieyohannan** [comment]
Hi @jmini thanks for this, and thanks for the great level of detail! I've spoken to engineering and they think if you daemonise the first process it should stay up. So you could try adding the `Wait for MockServer` step from you background services example to the first example in your blog post, and that should work. Let me know if this helps ☺️

**Comment by jmini** [comment]
I thought I tried it before writing, but now I did it again:

```yaml
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - run:
          name: Start MockServer
          command: mvn -Dmockserver.serverPort=1080 -Dmockserver.logLevel=INFO org.mock-server:mockserver-maven-plugin:5.9.0:runForked

      - run:
          name: Wait for MockServer
          command: |
            curl --retry 100 --retry-delay 5 --retry-connrefused --request PUT "http://localhost:1080/mockserver/reset"

      - run:
          name: Curl test
          # TODO: do something real instead of this placeholder command
          command: |
            curl --request PUT "http://localhost:1080/mockserver/reset"

      - run:
          name: Stop MockServer
          command: mvn -Dmockserver.serverPort=1080 org.mock-server:mockserver-maven-plugin:5.9.0:stopForked
          when: always
```

This does not work:

![Screenshot](https://user-images.githubusercontent.com/1222165/78330009-4bbc0400-7583-11ea-8188-9a32a05af2c2.png)

Basically the question is:
Are background processes started in a first step still running when next steps are executed if the script in the first step returned?

Or concretely in my case:
If in `Start MockServer` step I start a background task, when the script of this step returns with `0` what happen with the processes started during this step?

From your documentation:
https://circleci.com/docs/2.0/configuration-reference/#run

> Each `run` declaration represents a new shell. It’s possible to specify a multi-line command, each line of which will be run in the same shell.

I think that this implies that the process started in the first steps are no longer present in the next step. But your engineering told you otherwise, so now I am even more confused.

An other example (not using Mock-Server) could be useful.

---

I think I am not the only one with the issue of an HTTP server started in one step and not available in the next step:

* https://discuss.circleci.com/t/can-reach-localhost-using-curl-either-inside-or-outside-docker-container/15967
* https://discuss.circleci.com/t/cannot-curl-to-localhost-connection-refused/17885
