### ISSUE TITLE
shallow clone workaround doesn't work in config version 2.1

### ISSUE THREAD

**Issue by bark-frank** [circleci/circleci-docs#4223]
The solution in issue #2040 doesn't work in config version 2.1.  Whatever job that runs this as a step produces the error:

```
Error: Error calling workflow: 'build-and-test'
Error calling job: 'checkout_code'
Unclosed '<<' tag in string: '#!/bin/sh
set -e

and so on
```

Sample code of job running it as a step including workflow:

```
aliases:
  # Shallow Git Clone
  # https://discuss.circleci.com/t/shallow-clone-for-circleci-2-0-builds/20200
  - &checkout-shallow
    name: Checkout
    command: |
      #!/bin/sh
      set -e
      .... and so on ... from #2040

jobs:
  checkout_code:
    <<: *defaults-light
    steps:
      - run: *checkout-shallow
      - run: other stuff

...

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_code
      - other stuff
```
