### ISSUE TITLE
first windows example doesn't work

### ISSUE THREAD

**Issue by nicks** [circleci/circleci-docs#4257]
# Description
The first example on the Windows document doesn't work

# Location
https://circleci.com/docs/2.0/hello-world-windows/

# Steps to Reproduce

Here's the first example snippet the doc gives.

```

parameters:
      exec:
        type: executor
        default: win/default
    parallelism: 2
    working_directory: c:\\cache
    steps:
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            docker info
            docker run hello-world:nanoserver-1809
```

If I copy and paste that example into my circleci config, I get a validation error:

```
# ERROR IN CONFIG FILE:
# [#/jobs/build-windows] 0 subschemas matched instead of one
# 1. [#/jobs/build-windows] only 1 subschema matches out of 2
# |   1. [#/jobs/build-windows] no subschema matched out of the total 2 subschemas
# |   |   1. [#/jobs/build-windows] 0 subschemas matched instead of one
# |   |   |   1. [#/jobs/build-windows] required key [docker] not found
# |   |   |   2. [#/jobs/build-windows] required key [machine] not found
# |   |   |   3. [#/jobs/build-windows] required key [macos] not found
# |   |   2. [#/jobs/build-windows] required key [executor] not found
# |   |   |   A job must have one of `docker`, `machine`, `macos` or `executor` (which can provide docker/machine/macos information).
# 2. [#/jobs/build-windows] expected type: String, found: Mapping
# |   Job may be a string reference to another job

```

If I use snippets from later examples on the page. they work fine.

**Comment by teesloane** [comment]
Hi there @nicks - Did you copy the snippet as-is? If so, it is only representing an excerpt of what should go into your config.yml file. Let me know if that's the case, otherwise, we'll have a 🐞to fix.

**Comment by nicks** [comment]
Yes. It gave me that cryptic error message. Do you understand how to interpret that message?

The second example worked fine. It's worth pointing out that the first example and the second example use very different syntaxes, specifically:

```
executor:
      name: win/default # executor type
      size: "medium"
```

in the second example, and 

```
exec:
        type: executor
        default: win/default
```

in the first example. I couldn't find a good explanation for why they were so different.

**Comment by teesloane** [comment]
@nicks  Can you post your entire config in a comment? In the meantime, I will fix the conflicting examples (thanks for pointing that out).

**Comment by nicks** [comment]
Sure, here's the full example:

```
version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build-windows:
    parameters:
      exec:
        type: executor
        default: win/default
    parallelism: 2
    working_directory: c:\\cache
    steps:
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            docker info
            docker run hello-world:nanoserver-1809
workflows:
  version: 2
  build:
    jobs:
      - build-windows
```

here's the error:

```
#!/bin/sh -eo pipefail
# ERROR IN CONFIG FILE:
# [#/jobs/build-windows] 0 subschemas matched instead of one
# 1. [#/jobs/build-windows] only 1 subschema matches out of 2
# |   1. [#/jobs/build-windows] no subschema matched out of the total 2 subschemas
# |   |   1. [#/jobs/build-windows] 0 subschemas matched instead of one
# |   |   |   1. [#/jobs/build-windows] required key [docker] not found
# |   |   |   2. [#/jobs/build-windows] required key [machine] not found
# |   |   |   3. [#/jobs/build-windows] required key [macos] not found
# |   |   2. [#/jobs/build-windows] required key [executor] not found
# |   |   |   A job must have one of `docker`, `machine`, `macos` or `executor` (which can provide docker/machine/macos information).
# 2. [#/jobs/build-windows] expected type: String, found: Mapping
# |   Job may be a string reference to another job
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false

Exited with code exit status 1
CircleCI received exit code 1
```

Here's a version that works:

```
version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build-windows:
    executor:
      name: win/default
      size: "medium"
    steps:
      - run: choco install make

workflows:
  version: 2
  build:
    jobs:
      - build-windows
```

**Comment by teesloane** [comment]
Gotcha. Our docs are mis-aligned, so I will fix that. Again, in the meantime, here is a working config that calls out to docker (if you need it!)

```yaml
version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            docker info
            docker run hello-world:nanoserver-1809
```
