### ISSUE TITLE
Is it possible to use another CircleCI workflow as a step in a CircleCI workflow?

### ISSUE THREAD

**Issue by eszjay** [circleci/circleci-docs#4310]
# Missing Information
I have a repo with a set of tests I would like run at the end of every job in all of my repos to check basic functionality is preserved. Is there a way to include it in the other workflows without copying it to each repo?

# Already Looked
https://circleci.com/docs/2.0/workflows
https://circleci.com/docs/2.0/triggers
https://circleci.com/docs/2.0/api-job-trigger
https://circleci.com/docs/2.0/build-processing/#benefits-of-using-pipelines

# Potential Locations
https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs

**Comment by rosieyohannan** [comment]
Hey! Thanks for getting in touch about this. I've had a chat with our engineering team about the best way forward for your use case, and something along the lines of this should be possible:

```
steps:
  - run: git clone git@github.com:some/otherrepo.git standard-tests
  - run:
      working_directory standard-tests
      command: ./run-tests
```

Then, you can use the config to author an orb to share this across multiple repos. We have several sections in our docs on orbs, starting here: https://circleci.com/docs/2.0/orb-intro/#section=configuration.

Please let me know if you have more questions! ☺️
