### ISSUE TITLE
RE: jekyll/_docs/configuration.md

### ISSUE THREAD

**Issue by jdforsythe** [circleci/circleci-docs#455]
The code for changing the PhantomJS version is wrong:

```yml
machine:
  pre:
    - curl -k -L -o phantomjs.tar.bz2 http://phantomjs.googlecode.com/files/phantomjs-1.8.2-linux-x86_64.tar.bz2
```

is a 404
