### ISSUE TITLE
Using `nvmrc` to dictate the node version so development + CI match

### ISSUE THREAD

**Issue by kylemh** [circleci/circleci-docs#4581]
# Missing Information
Googling "circleci nvmrc" and "circleci nvm" and "use nvmrc for node version circleci" yield a few support questions, but it would be nice if there was an official answer or paradigm of support on this documented.

# Already Looked
- Google searches described above
- https://circleci.com/docs/?query=nvmrc yields one potentially relevant solution in [this article](https://circleci.com/docs/2.0/language-javascript/), but a quick CTRL+F yields no results for "nvm".

# Potential Locations
I should be able to search the CircleCI docs for this item certainly. If not there, I'd hope it'd be referenced somewhere in a more official manner such that google results place it highly.

**Comment by jmurret** [comment]
Hi @kylemh,  you will just need to specify a docker image that has node and nvm installed.  You could find a published one on docker hub or another registry.  Or you could built and publish your own.  Then specify it in your configuration.

So here you could take our starter config for a node app that looks like this:
```
version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: cimg/node:13.11
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
```

And change the docker image so that it is:
```
```
version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: thomasr8/node-nvm:latest
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
```

If it were me, I would publish my own docker image that had nvm as well as the supported versions of node that my team uses.  This reason alone is why we have not hosted such an image.  We could host nvm but we would bloat an image and slow down docker pulls for users by having to load tons of versions.
I would publish your own public image to docker hub with the node versions you need + nvm.

I hope this helps.
```
