### ISSUE TITLE
The latest node:erbium-stretch image breaks `npm install` of `mmmagic`

### ISSUE THREAD

**Issue by thomasmost** [circleci/circleci-docs#4600]
# Description
The latest node:erbium-stretch image breaks our `npm install` step

# Location
This occurred in our test suite pipeline using the latest erbium-stretch image.

# Steps to Reproduce
Here's our executor config:
```yml
  executor:
    docker:
        - image: circleci/node:erbium-stretch
    resource_class: medium+
```

and our `npm install` command:

```yml

  npm_install:
    description: "restores/install node modules"
    steps:
       - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.8.0'
       - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
       - run:
          name: install-npm
          command: npm ci
       - run:
          name: rebuild-modules
          command: npm rebuild bcrypt --build-from-source node-expat mmmagic
       - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
```

The error:

```
make: Leaving directory '/home/circleci/project/node_modules/mmmagic/build'
gyp info ok 

> protobufjs@6.8.8 postinstall /home/circleci/project/node_modules/protobufjs
> node scripts/postinstall

npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2020-07-29T15_21_52_635Z-debug.log
```
I believe this indicates that the `mmmagic` package is the problem... from our package.json:

```json
  "dependencies": {
    "mmmagic": "0.5.3",
  }
```
