### ISSUE TITLE
Add an example of logic that uses executor

### ISSUE THREAD

**Issue by briceicle** [circleci/circleci-docs#4637]
# Missing Information
- Update the Logic Statement section to show a YAML alias can be used as a logic statement
- Add an example to show how to compare executors

Here's an example config
```
version: 2.1

executors:
  linux-13:
    docker:
      - image: cimg/node:13.13
  macos: &macos-executor
    macos:
      xcode: 11.4

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - when:
          condition:
            equal: [ *macos-executor, << parameters.os >> ]
          steps:
            - run: echo << parameters.node-version >>
      - run: echo 0

workflows:
  all-tests:
    jobs:
      - test:
          os: macos
          node-version: "13.13.0"
```

# Already Looked
https://circleci.com/docs/2.0/configuration-reference/#logic-statements
https://circleci.com/docs/2.0/configuration-reference/#logic-statement-examples

# Potential Locations
https://circleci.com/docs/2.0/configuration-reference/#logic-statements
https://circleci.com/docs/2.0/configuration-reference/#logic-statement-examples
