### ISSUE TITLE
question: is it possible to use regex, wildcards or 'contains' in logic statements ("using when in workflows")?

### ISSUE THREAD

**Issue by wlad** [circleci/circleci-docs#4672]
# Location
https://circleci.com/docs/2.0/configuration-reference/#logic-statement-examples

# Explanation
you give the following example:

```
workflows:
  my-workflow:
      when:
        condition:
          or:
            - equal: [ master, << pipeline.git.branch >> ]
```

## Question 1
Is it possible to use regex or wildcards? i.e.

```
workflows:
  my-workflow:
      when:
        condition:
          or:
            - equal: [ feature/*, << pipeline.git.branch >> ]
            - equal: [ bugix/*, << pipeline.git.branch >> ]
```

## Question 2 (feature request)
besides `equal` will there be a `contains` in the future? i.e.

```
workflows:
  my-workflow:
      when:
        condition:
          or:
            - contains: [ feature/, << pipeline.git.branch >> ]
```

Thank You! ❤️
