### ISSUE TITLE
How to test with several jdks

### ISSUE THREAD

**Issue by apupier** [circleci/circleci-docs#4912]
# Missing Information

I would like to know how to configure a matrix of jobs with different JDKs

# Already Looked

https://circleci.com/docs/2.0/language-java/
https://circleci.com/blog/circleci-matrix-jobs/
https://circleci.com/developer/orbs/orb/circleci/maven#executors

# Potential Locations

in https://circleci.com/docs/2.0/language-java/

**Comment by teesloane** [comment]
Hi!

Here's an example config using multiple JDKS.  Let me know if this works!

```
version: 2.1 

# This section is not required; but it can be used to share config across multiple jobs/steps.
commands:
  # a command for restoring your cache
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
  # a command for saving your cache
  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  # a test command
  test:
    steps:
      - checkout
      - restore_cache_cmd
      - run: ./mvnw test
      - save_cache_cmd


jobs:
 # you might have several jobs in your config,
 # but this job below exemplifies a matrix build:
  test-with-docker:
    parameters: # we need to declare a parameter (which can be named anything)
      jdk-version: 
        type: string 
    docker:
      - image: circleci/openjdk:<<parameters.jdk-version>> # here we interpolate our parameter.
    steps:
      - test

workflows:
  matrix-test: 
    jobs:
      - test-with-docker2:
          matrix:
            parameters:
              jdk-version: ["9.0.4-12", "stretch", "8"] # this value can be any arbitrary tage that is available for the docker image you are using.

```
