### ISSUE TITLE
More details for logic statements docs

### ISSUE THREAD

**Issue by SashaLsnko** [circleci/circleci-docs#4938]
# Missing Information
There is a new behaviour for logic statements I'm adding (regarding `and`, `or`, `equal`)
- using logic with an empty list of arguments fails validation
```
- equal: []
```
- using logic with no arguments is falsy
```
when:
  and:
    - equal:
    - << pipeline.parameters.deploy-canary >>  
```

# Location
https://circleci.com/docs/2.0/configuration-reference/#logic-statements
