### ISSUE TITLE
Provided parameters example is invalid, according to 'circleci config validate'

### ISSUE THREAD

**Issue by nateww** [circleci/circleci-docs#4956]
# Locations
https://circleci.com/docs/2.0/env-vars/
OR
https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/env-vars.md

# Details

In the section, defined by the following text:
```
Using version:2.1 config, you can reuse pieces of config across your config.yml. By using the parameters declaration, you can interpolate (or, "pass values") into reusable commands jobs and executors:
```

Specifically, the example text:
```
version: 2.1

jobs:
  parameters:
    org_name:
      type: string
      default: my_org
    repo_name:
      type: string
      default: my_repo
  my_job:
    docker:
      - circleci/node:12.15.0
    working_directory: /go/src/github.com/<< parameters.org_name >>/<< parameters.repo_name >>
```

If I create a `config.yml` file with the above content, and run `circleci config validate` on the resulting file, I get an error.

```
% circleci config validate
Error: ERROR IN CONFIG FILE:
[#/jobs] 11 schema violations found
Any string key is allowed as job name.
1. [#/jobs/my_job] 0 subschemas matched instead of one
|   1. [#/jobs/my_job] only 1 subschema matches out of 2
|   |   1. [#/jobs/my_job] 2 schema violations found
|   |   |   1. [#/jobs/my_job] required key [steps] not found
|   |   |   2. [#/jobs/my_job/docker/0] expected type: Mapping, found: String
|   |   |   |   SCHEMA:
|   |   |   |     type: object
|   |   |   |   INPUT:
|   |   |   |     circleci/node:12.15.0
|   2. [#/jobs/my_job] expected type: String, found: Mapping
|   |   Job may be a string reference to another job
2. [#/jobs/parameters] 0 subschemas matched instead of one
|   1. [#/jobs/parameters] only 0 subschema matches out of 2
|   |   1. [#/jobs/parameters] no subschema matched out of the total 2 subschemas
|   |   |   1. [#/jobs/parameters] 0 subschemas matched instead of one
|   |   |   |   1. [#/jobs/parameters] required key [docker] not found
|   |   |   |   2. [#/jobs/parameters] required key [machine] not found
|   |   |   |   3. [#/jobs/parameters] required key [macos] not found
|   |   |   2. [#/jobs/parameters] required key [executor] not found
|   |   |   |   A job must have one of `docker`, `machine`, `macos` or `executor` (which can provide docker/machine/macos information).
|   |   2. [#/jobs/parameters] 3 schema violations found
|   |   |   1. [#/jobs/parameters] extraneous key [org_name] is not permitted
|   |   |   |   Permitted keys:
|   |   |   |     - description
|   |   |   |     - parallelism
|   |   |   |     - macos
|   |   |   |     - resource_class
|   |   |   |     - docker
|   |   |   |     - steps
|   |   |   |     - working_directory
|   |   |   |     - machine
|   |   |   |     - environment
|   |   |   |     - executor
|   |   |   |     - shell
|   |   |   |     - parameters
|   |   |   |   Passed keys:
|   |   |   |     - org_name
|   |   |   |     - repo_name
|   |   |   2. [#/jobs/parameters] extraneous key [repo_name] is not permitted
|   |   |   |   Permitted keys:
|   |   |   |     - description
|   |   |   |     - parallelism
|   |   |   |     - macos
|   |   |   |     - resource_class
|   |   |   |     - docker
|   |   |   |     - steps
|   |   |   |     - working_directory
|   |   |   |     - machine
|   |   |   |     - environment
|   |   |   |     - executor
|   |   |   |     - shell
|   |   |   |     - parameters
|   |   |   |   Passed keys:
|   |   |   |     - org_name
|   |   |   |     - repo_name
|   |   |   3. [#/jobs/parameters] required key [steps] not found
|   2. [#/jobs/parameters] expected type: String, found: Mapping
|   |   Job may be a string reference to another job
```

FYI
```
% circleci version
0.1.11508+10b61a8 (homebrew)
```

**Comment by teesloane** [comment]
Hi @nateww - sorry you are running into some issues here. The example you reference is incomplete (I will replace it shortly). Here is an example of a full config that makes use of job-parameters:

```
version: 2.1

jobs:
  build:
    parameters:
      org_name:
        type: string
        default: my_org
      repo_name:
        type: string
        default: my_repo
    docker:
      - image: circleci/node:12.15.0
    steps:
      - run: echo "project directory is go/src/github.com/<< parameters.org_name >>/<< parameters.repo_name >>"

workflows:
  my_workflow:
    jobs:
      - build:
          org_name: my_organization
          repo_name: project1

      - build:
          org_name: my_organization
          repo_name: project2

```

Where the running of the job "build" with two different sets of parameters will result in the following respective results:

```
project directory is go/src/github.com/my_organization/project1
CircleCI received exit code 0
```
and

```
project directory is go/src/github.com/my_organization/project2
CircleCI received exit code 0
```

Let me know if this helped!

**Comment by nateww** [comment]
Unfortunately, that doesn't quite work for me. I was looking to create parameters that were global to ALL of the jobs, not parameters for a single job.  I was trying to define a parameter that could be shared for both a `build` and a `deploy` job.  Yes, I could use environment variables, but they are not shell expanded when defining other environment variables.

ie;
```
version: 2.1

jobs:
   parameters:
      notification_host:
        type: string
        default: notify.rest.com
  build:
    environment: 
      NOTIFY_URL=https://<< parameters.notification_host >>/building
    docker:
      - image: circleci/node:12.15.0
    steps:
      - run: curl -XPOST -sS $NOTIFY_URL -d "Building $CIRCLE_BRANCH"
...
  deploy:
    environment: 
      NOTIFY_URL=https://<< parameters.notification_host >>/deploying
..
    steps:
      - run: curl -XPOST -sS $NOTIFY_URL -d "Deploying $CIRCLE_BRANCH"
```

Yeah, the example is somewhat arbitrary, but hopefully that makes sense.

**Comment by nateww** [comment]
It appears that I may be able to use pipeline parameters to solve the problem.

```
version: 2.1

parameters:
  notification_host:
    type: string
    default: notify.rest.com

jobs:
  build:
    environment: 
      NOTIFY_URL=https://<< pipeline.parameters.notification_host >>/building
    docker:
      - image: circleci/node:12.15.0
    steps:
      - run: curl -XPOST -sS $NOTIFY_URL -d "Building $CIRCLE_BRANCH"
...
  deploy:
    environment: 
      NOTIFY_URL=https://<< pipeline.parameters.notification_host >>/deploying
..
    steps:
      - run: curl -XPOST -sS $NOTIFY_URL -d "Deploying $CIRCLE_BRANCH"
```
