### ISSUE TITLE
machine/resource_class stanzas in config reference do not reflect possibility for runner configuration

### ISSUE THREAD

**Issue by aaronstillwell** [circleci/circleci-docs#5019]
# Locations
https://circleci.com/docs/2.0/configuration-reference/#machine-executor-linux
https://circleci.com/docs/2.0/configuration-reference/#resource_class

# Details
The `machine` and `resource_class` stanzas as detailed in the configuration reference do not reflect that they can now be used to configure usage of the runner.

E.g

```
jobs:
  job_name:
    machine: true
    resource_class: my-namespace/my-runner
```
