### ISSUE TITLE
custom matrix parameters not supported

### ISSUE THREAD

**Issue by ericvergnaud** [circleci/circleci-docs#5044]
# Description
I am trying to implement a matrix with a custom dimension, as follows:
 ```yaml         
.../...
  matrix:
    parameters:
      target: [ "dart", "go", "python2", "python3", "javascript" ]
```
Whether I submit this via git or via the online config editor, it is not recognized, I get the following error:
_Unexpected argument(s): target_

Adding a parameter definition doesn't help:
```yaml
parameters:
  target:
    type: enum
    default: ""
    enum: [ "", "dart", "go", "python2", "python3", "javascript" ]
```

This could be a documentation bug, but according to various forums I assume building a matrix of jobs using custom variables is supported by CircleCI ?

# Location
https://app.circleci.com/projects/github/antlr/antlr4/circleci-project-setup/config.

# Steps to Reproduce
Try editing the config

**Comment by ericvergnaud** [comment]
Providing the non-working config here because I dropped matrix usage for now (issue is blocking)
``` yaml
version: 2.1

orbs:
  maven: circleci/maven@1.1.0

jobs:
  test_java_tool_and_runtime:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: build tool
          command: mvn -B -V -DskipTests=true -Dmaven.javadoc.skip=true install
      - run:
          name: test runtime
          command: |
            cd runtime-testsuite
            mvn -q -Dparallel=methods -DthreadCount=4 -Dtest=java.* test
            cd ..
      - run:
          name: test tool
          command: |
            cd tool-testsuite
            mvn -q -Dparallel=methods -DthreadCount=4 test
            cd ..
  test_fast_runtime:
    docker:
      - image: cimg/openjdk:8.0
    environment:
      TARGET: << matrix.target >>
    steps:
      - checkout
      - run:
          name: build tool
          command: mvn -B -V -DskipTests=true -Dmaven.javadoc.skip=true install
      - run:
          name: install << matrix.target >> pre-requisites
          command: |
            f=".circleci/scripts/install-linux-$TARGET.sh"; ! [ -x "$f" ] || "$f"
      - run:
          name: test tool
          command: |
            .circleci/scripts/run-tests-linux-$TARGET.sh
  test_slow_runtime:
    docker:
      - image: cimg/openjdk:8.0
    environment:
      TARGET: << matrix.target >>
      GROUP: << matrix.group >>
    steps:
      - checkout
      - run:
          mvn -B -V -DskipTests=true -Dmaven.javadoc.skip=true install
      - run: |
          f=".circleci/scripts/install-linux-$TARGET.sh"; ! [ -x "$f" ] || "$f"
      - run: |
          .circleci/scripts/run-tests-linux-$TARGET.sh

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - test_java_tool_and_runtime
      - test_fast_runtime:
          matrix:
            parameters:
              target: [ "dart", "go", "python2", "python3", "javascript" ]
      - test_slow_runtime:
          matrix:
            parameters:
              target: [ "cpp", "dotnet", "swift" ]
              group: [ "LEXER", "PARSER", "RECURSION" ]
```

**Comment by ericvergnaud** [comment]
Interestingly, if you take the canonical example you also face problems:

```yaml
version: 2.1

jobs:
  sayhello: # defines a parameterized job
    description: A job that does very little other than demonstrate what a parameterized job looks like
    parameters:
      saywhat:
        description: "To whom shall we say hello?"
        default: "World"
        type: string
    machine: true
    steps:
      - run: echo "Hello << parameters.saywhat >>"

workflows:
  build:
    jobs:
      - sayhello: # invokes the parameterized job
          saywhat: Everyone
```
Edit the above in the config editor, then replace 'saywhat' by 'stuff' in both the job and the workflow: the editor will yell, complaining that 'saywhat' parameter is missing
