### ISSUE TITLE
Add explicit example if/how templates are evaluated when using anchors and aliases

### ISSUE THREAD

**Issue by bottlenecked** [circleci/circleci-docs#5060]
# Missing Information
In the [writing-yaml](https://circleci.com/docs/2.0/writing-yaml/#anchors-and-aliases) page in the docs there's mention of aliasing and using anchors, but it's unclear if templates inside strings will be evaluated or not.
I believe explicitly stating if template evaluation is supported would be beneficial. If supported, a note on when the evaluation happens might also be useful: e.g. assuming `{{ epoch }}` is used, would 2 different values be output between capture and usage?

## What it could look like if supported
```yaml
song:
  - &name 'System {{ arch }}'
  - You
  - can
  - call
  - me
  - *name

# produces 

song:
  - System darwin x64
  - You
  - can
  - call
  - me
  - System darwin x64
```

## What it could look like if not supported

_Note_: template evaluation is __not__ supported when evaluating anchors

# Already Looked
- Circle ci docs: https://circleci.com/docs/2.0/writing-yaml/ and https://circleci.com/docs/2.0/reusing-config/
- google search: https://www.google.com/search?q=circleci+anchor+alias+template+evaluation

# Potential Locations
Should probably be a part of the Writing Yaml document
