### ISSUE TITLE
CirclceCI fails to build a typescript project 

### ISSUE THREAD

**Issue by kona86** [circleci/circleci-docs#5177]
# Description
Describe the bug you found.
CirclceCI fails to build a typescript project 
# Location
Describe where you caught the bug.
If the bug occurs in a specific document,
add the link here.
I caugt the bug on the online platform known at https://app.circleci.com/

# Steps to Reproduce
Describe the steps you took to produce the bug.
a postinstall script npm run build  byuild a typescript project
does not work on  online infastructure system

**Comment by teesloane** [comment]
Hi there, you'll have to provide more information for us to be able to help (post your `.circleci/config.yml`,  provide error details etc).

**Comment by kona86** [comment]
After a series of unsuccessful attempt,I have manage to build on run on circleci.The problem I seemed to have encountered
was that circleci maybe the config reads the post install script run it as part of the installing of npm dependencies.

I am not so good with circleci configuration,but I changed my package.json from
```json 
 "scripts": {
        "test": " mocha -r esm ./test/**/*.spec.js",
        "build": "tsc",
        "build:watch": "tsc --watch",
        "postinstall":"npm run build"
    },
    ```
    to ````json
 "scripts": {
        "test": "npm run build & mocha -r esm ./test/**/*.spec.js",
        "build": "tsc",
        "build:watch": "tsc --watch"
    },
    ```
    I would like a circleci config to support the formal package.json script.
```yml
Here is my current config
version: 2.1
orbs:
    node: circleci/node@3.0.0
workflows:
    node-tests:
        jobs:
            - node/test
```

**Comment by teesloane** [comment]
Hi there @kona86. I may be misunderstanding but it looks like you may have encountered an issue with using the node orb and running specific commands in your package json. If you check out the node [orb source](https://circleci.com/developer/orbs/orb/circleci/node) you'll see that the `node/test` job will by default run the `npm  test` command. If you want to switch the command run, you can change it like so:

```
version: 2.1
orbs:
    node: circleci/node@3.0.0
workflows:
    node-tests:
        jobs:
            - node/test
                run-command: <insert name of npm command here
```

I think your change to include your build command into the test command is probably the best solution. Since it sounds like you got it working I will be closing this issue for now.
