### ISSUE TITLE
GPU executer's  nvidia driver is not working

### ISSUE THREAD

**Issue by ranrubin** [circleci/circleci-docs#5371]
# Description
GPU executer nvidia driver is not working

# Location
[using gpus](https://circleci.com/docs/2.0/executor-types/?utm_medium=SEM&utm_source=gnb&utm_campaign=SEM-gb-DSA-Eng-emea&utm_content=&utm_term=dynamicSearch-&gclid=CjwKCAjw47eFBhA9EiwAy8kzNJ3DoHmqd8d7xh9xK4XBAbneNYLvME1ZnBaLaphWvYjJ1j2w9U8S-xoCQLIQAvD_BwE#using-gpus)

# Steps to Reproduce

I followed the doc and ran:

```
version: 2.1
jobs:
  build:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - run: nvidia-smi
```
got
```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

The driver is not configured properly
