### ISSUE TITLE
RE: jekyll/_docs/yarn.md

### ISSUE THREAD

**Issue by callumlocke** [circleci/circleci-docs#543]
The [Circle CI page on using yarn](https://circleci.com/docs/yarn/) says:

> Yarn is pre-installed on CircleCI

So I configured Circle to use `yarn` to install dependencies, but I get this:

![image](https://cloud.githubusercontent.com/assets/250617/22203386/c1127a1a-e164-11e6-95da-afa03ca01730.png)

Here is my full `circle.yml` config:

```yml
machine:
  timezone: Europe/London
  node:
    version: stable
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"

dependencies:
  cache_directories:
    - ~/.cache/yarn
    - bower_components
    - node_modules
  override:
    - yarn

test:
  override:
    - yarn test
  post:
    - yarn run preflight

deployment:
  s3: # this is just a custom name, could be anything
    branch: /.*/
    commands:
      - yarn run deploy:confirm

general:
  artifacts:
    - dist
```
