### ISSUE TITLE
RE: jekyll/_docs/yarn.md

### ISSUE THREAD

**Issue by afiedler** [circleci/circleci-docs#559]
I'm getting an error when I follow these directions. The error is in the Dependencies section of CircleCI and looks like this:

```
yarn
bash: line 1: yarn: command not found

yarn returned exit code 127

Action failed: yarn
```

This is after a "Rebuild without cache". My circle.yml file looks like this (with some deployment lines omitted):

```
machine:
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
  node:
    version: 6.9.0
dependencies:
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
general:
  artifacts:
    - "coverage/"
test:
  override:
    - webdriver-manager update --standalone
    - gulp unit-test-app --env=build
    - gulp lint --env=build
```

When I change the `dependencies` section to this, I'm able to successfully get yarn to work, but it would be great to avoid installing yarn each time:
```
dependencies:
  override:
    - "curl -o- -L https://yarnpkg.com/install.sh | bash"
    - "source ~/.bashrc"
```

Thanks for any help!
