### ISSUE TITLE
Windows executor contains Python version with bug when using envs

### ISSUE THREAD

**Issue by NickScottKortical** [circleci/circleci-docs#5729]
# Description
Creating a python virtual environment using the command `python -m venv <name_of_venv>` fails with the following error:
```
Error: [Errno 2] No such file or directory: 'C:\\tools\\miniconda3\\lib\\venv\\scripts\\nt\\python.exe'
```
A directory for the venv is created which contains subdirectories eg. Scripts, however the directories are empty (missing the .bat files)

The documentation mentions that this executor comes with python 3.7.3 installed, however the python installed is unable to create environments, is there a specific way the pre installed python should be being used?

# Location
When running a build

# Steps to Reproduce
The following config should reproduce the bug:

```
version: 2.1
orbs:
  win: circleci/windows@2.4.1
jobs:
  build_windows:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - run:
          name: Create venvs
          command: |
            set -e
            python -m venv build_venv
workflows:
  version: 2
  build:
    jobs:
      - build-windows
```
