### ISSUE TITLE
Almost all your database setup example not working!

### ISSUE THREAD

**Issue by han-characters** [circleci/circleci-docs#5747]
Your docs are not working:

https://circleci.com/docs/2.0/databases/
https://discuss.circleci.com/t/config-circleci-for-mysql-database/19954/3

```
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-apache-node-browsers # The primary container where steps are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      - image: circleci/mysql:8.0.4
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd

    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u user -ppassw0rd test_db < sql-data/dummy.sql
            mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT * FROM test_db.Persons"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
```

I'm just trying it out and just simply put those examples into my empty project config. Non of them worked. Can you please give me a working Mysql + Node config example?

Thanks.

**Comment by han-characters** [comment]
Some errors:
```
#!/bin/bash -eo pipefail
sudo apt-get install default-mysql-client
mysql -h 127.0.0.1 -u user -ppassw0rd test_db < sql-data/dummy.sql
mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT * FROM test_db.Persons"

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libaio1 libconfig-inifiles-perl libdbd-mysql-perl libdbi-perl libreadline5
  libsnappy1v5 libterm-readkey-perl mariadb-client-10.3
  mariadb-client-core-10.3
Suggested packages:
  libclone-perl libmldbm-perl libnet-daemon-perl libsql-statement-perl
The following NEW packages will be installed:
  default-mysql-client libaio1 libconfig-inifiles-perl libdbd-mysql-perl
  libdbi-perl libreadline5 libsnappy1v5 libterm-readkey-perl
  mariadb-client-10.3 mariadb-client-core-10.3
0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 7927 kB of archives.
After this operation, 54.2 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 libconfig-inifiles-perl all 3.000001-1 [51.9 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 libaio1 amd64 0.3.112-3 [11.2 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 libreadline5 amd64 5.2+dfsg-3+b13 [120 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 libsnappy1v5 amd64 1.1.7-1 [17.0 kB]
Err:5 http://deb.debian.org/debian buster/main amd64 mariadb-client-core-10.3 amd64 1:10.3.18-0+deb10u1
  404  Not Found [IP: 199.232.130.132 80]
Err:6 http://deb.debian.org/debian buster/main amd64 mariadb-client-10.3 amd64 1:10.3.18-0+deb10u1
  404  Not Found [IP: 199.232.130.132 80]
Get:7 http://deb.debian.org/debian buster/main amd64 default-mysql-client all 1.0.5 [3532 B]
Err:8 http://deb.debian.org/debian buster/main amd64 libdbi-perl amd64 1.642-1+b1
  404  Not Found [IP: 199.232.130.132 80]
Get:9 http://deb.debian.org/debian buster/main amd64 libdbd-mysql-perl amd64 4.050-2 [121 kB]
Get:10 http://deb.debian.org/debian buster/main amd64 libterm-readkey-perl amd64 2.38-1 [27.4 kB]
Fetched 352 kB in 0s (708 kB/s)                  
E: Failed to fetch http://deb.debian.org/debian/pool/main/m/mariadb-10.3/mariadb-client-core-10.3_10.3.18-0+deb10u1_amd64.deb  404  Not Found [IP: 199.232.130.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/m/mariadb-10.3/mariadb-client-10.3_10.3.18-0+deb10u1_amd64.deb  404  Not Found [IP: 199.232.130.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/libd/libdbi-perl/libdbi-perl_1.642-1+b1_amd64.deb  404  Not Found [IP: 199.232.130.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Exited with code exit status 100
CircleCI received exit code 100
```

```
#!/bin/bash -eo pipefail
for i in `seq 1 10`;
do
  nc -z localhost 3306 && echo Success && exit 0
  echo -n .
  sleep 1
done
echo Failed waiting for MySQL && exit 1

..........Failed waiting for MySQL

Exited with code exit status 1
CircleCI received exit code 1
```
I tried those out in my local, it works fine, but I couldn't get it working in CircleCI.

**Comment by han-characters** [comment]
I have figured the issue. It's about the default MySQL environment variable.

```
environment:
  MYSQL_ROOT_PASSWORD: rootpw
  MYSQL_DATABASE: test_db
  MYSQL_USER: user
  MYSQL_PASSWORD: passw0rd
``` 

For some reason, above envs are not working in my config. But if I only set

```
MYSQL_DATABASE
MYSQL_USER
MYSQL_PASSWORD
```

and not setting `MYSQL_USER` to `root`, it will work.


Reference:
https://stackoverflow.com/questions/45086162/docker-mysql-error-1396-hy000-operation-create-user-failed-for-root
