### ISSUE TITLE
Clarify how to use yarn with private packages (_cci1/yarn.md)

### ISSUE THREAD

**Issue by rosskevin** [circleci/circleci-docs#593]
[Reference discussion](https://discuss.circleci.com/t/yarn-with-private-packages/10157)

If `pre`-generating an `.npmrc` is correct way to use private packages with yarn, please update the yarn doc with:

```yaml
dependencies:
  pre:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
```

Otherwise, please update the doc with the preferred method.

Thank you
