### ISSUE TITLE
Buildx with remote docker executor

### ISSUE THREAD

**Issue by andormarkus** [circleci/circleci-docs#6034]
Hi Support Team,

I'm sorry to open this issue here, but your [other repo](https://github.com/CircleCI-Public/support-articles) does not support issues.

I have followed the support article [[How To Use Docker Buildx in Remote Docker?](https://support.circleci.com/hc/en-us/articles/360058095471-How-To-Use-Docker-Buildx-in-Remote-Docker-)] but whit the given configuration none of my built started/succeeded. 

With the following setup, I was able to run buildx for multi-arch building

```yaml
- setup_remote_docker:
    version: 20.10.11
- run:
    name: Create a new docker buildx builder instance
    command: |
      docker run --privileged --rm tonistiigi/binfmt --install all
      docker context create multiarch-builder
      docker buildx create --use multiarch-builder
```

Thanks,
Andor
