### ISSUE TITLE
Boolean Conditionals 

### ISSUE THREAD

**Issue by gilley-st** [circleci/circleci-docs#6078]
# Missing Information
On this page https://circleci.com/docs/2.0/reusing-config/#using-the-parameters-declaration, I found this line:
<<# parameters.all >> -a <</ parameters.all >><<^ parameters.short >> -l <</ parameters.short >>
I take it that the # is an if-statement and the ^ is the else-if-statement.  It would be great to have a dedicated section explaining the HTML like markup as well any additional functionality not shown in examples.  For instance, how would one do an else-statement? 

# Already Looked
On top of the below links, I did some Google searches, but I am not sure the keywords to use
https://circleci.com/docs/2.0/reusing-config/
https://circleci.com/docs/2.0/env-vars/

# Potential Locations
I'd expect it to be here https://circleci.com/docs/2.0/env-vars/
Thank you for looking into this!

**Comment by devinmarieb** [comment]
Hi @gilley-st -- The syntax here is actually [mustache syntax](http://mustache.github.io/mustache.5.html). If you'd like to create more complex conditional statements, I would suggest looking at some mustache examples. We have a new example we are going to replace the boolean examples with which hasn't been merged yet. The replacement for a boolean example will go something like this:
```
version: 2.1
commands:
  npm-install:
    parameters:
      clean:
        description: Perform a clean install
        type: boolean
        default: false
    steps:
      - when:
          condition: << parameters.clean >>
          steps:
            - run: npm clean-install
      - when:
          condition:
            not: << parameters.clean >>
          steps:
            - run: npm install
```
