### ISSUE TITLE
Scheduled Pipelines: can we continue to use regex branch filtering

### ISSUE THREAD

**Issue by GaxZE** [circleci/circleci-docs#6148]
# Missing Information
Scheduled pipelines, there is nothing stated about or examples of regex branch filters.

# Already Looked
https://circleci.com/blog/using-scheduled-pipelines/
https://circleci.com/docs/2.0/scheduled-pipelines/

# Potential Locations
https://circleci.com/docs/2.0/scheduled-pipelines/

**Comment by Maxwell2022** [comment]
@kbatuigas this is not working, triggering tags is `v1.0.0` and the regex should match

```yaml
version: 2.1

[...]

workflows:
  [...]
  production:
    when:
      matches:
        pattern: /v[0-9]+(\.[0-9]+)*([^-])*$/
        value: << pipeline.git.tag >>
    jobs:
      - job_1
      - job_2
```

Outcome: 
<img width="481" alt="image" src="https://user-images.githubusercontent.com/670701/154192728-ce490419-a8da-42c3-92dd-b29533171ce7.png">

I've read that each jobs needs to have the tag filter for them to be executed, this is not specified in the doc and is really counter intuitive when it's working find for branches

For instance another user being frustrated with this: https://discuss.circleci.com/t/use-of-pipeline-git-tag-in-workflows-name-when/36159/3
