### ISSUE TITLE
Pattern matching with when condition for workflows does not work for Git tags

### ISSUE THREAD

**Issue by iwt-sebastian-hesse-extern** [circleci/circleci-docs#6375]
# Description
Hi, I have tried to use a `when` condition for workflows and wanted to match Git tags but I ran into a problem there that it never matches, regardless of how I setup the `when` condition (using CircleCI Cloud and version 2.1).

All of the following examples do **NOT** match a new Git tag like `1.2.3`:

```
version: 2.1

jobs:
  init:
    # think about some job steps here

workflows:
  test-when-condition-1:
    when: << pipeline.git.tag >>
    jobs:
      - init
  test-when-condition-2:
    when:
      matches:
        pattern: '^\d+.\d+.\d+$'
        value: << pipeline.git.tag >>
    jobs:
      - init
  test-when-condition-3:
    when:
      matches:
        pattern: /^\d+.\d+.\d+$/
        value: << pipeline.git.tag >>
    jobs:
      - init
  test-when-condition-4:
    when:
      matches:
        pattern: ^\d+.\d+.\d+$
        value: << pipeline.git.tag >>
    jobs:
      - init
  test-when-condition-5:
    when:
      and:
        - matches:
            pattern: '^\d+.\d+.\d+$'
            value: << pipeline.git.tag >>
    jobs:
      - init
  test-when-condition-6:
    when:
      and:
        - matches:
            pattern: /^\d+.\d+.\d+$/
            value: << pipeline.git.tag >>
    jobs:
      - init
  test-when-condition-7:
    when:
      and:
        - matches:
            pattern: ^\d+.\d+.\d+$
            value: << pipeline.git.tag >>
    jobs:
      - init
  test-when-condition-8:
    when:
      matches: { pattern: '^\d+.\d+.\d+$', value: << pipeline.git.tag >> }
    jobs:
      - init
  test-when-condition-9:
    when:
      matches: { pattern: /^\d+.\d+.\d+$'/, value: << pipeline.git.tag >> }
    jobs:
      - init
  test-when-condition-10:
    when:
      matches: { pattern: ^\d+.\d+.\d+$, value: << pipeline.git.tag >> }
    jobs:
      - init
  test-when-condition-11:
    when:
      and:
        - matches: { pattern: '^\d+.\d+.\d+$', value: << pipeline.git.tag >> }
    jobs:
      - init
  test-when-condition-12:
    when:
      and:
        - matches: { pattern: /^\d+.\d+.\d+$/, value: << pipeline.git.tag >> }
    jobs:
      - init
  test-when-condition-13:
    when:
      and:
        - matches: { pattern: ^\d+.\d+.\d+$, value: << pipeline.git.tag >> }
    jobs:
      - init
```

## Explanation

For `test-when-condition-1` I'd expect that the pipeline value resolves to a truthy value but that doesn't work. However, I doubt that it's related to the way I'm using this shorthand syntax of `when` because in another workflow I'm already using `when: << pipeline.parameters.my_parameter >>` and it works as expected.

For `test-when-condition-2`, `test-when-condition-3`, `test-when-condition-4` I'm using several variations of `pattern` because the documentation and your implementation aren't really clear. For example, your documentation about [logic statements](https://circleci.com/docs/2.0/configuration-reference/#logic-statements) recommends using double quotes `"` but if I do that, a validation error appears under app.circleci.com: `Unable to parse YAMLwhile scanning a double-quoted scalar in 'string'`. Hence, I tried single quotes `'` as well as no quotes (like `^\d+.\d+.\d+$`) or a pattern like I'm using it with `filters` for a single job (like ` /^\d+.\d+.\d+$/` with slashes `/` around the pattern). None of that works and triggers my workflow.

For `test-when-condition-5`, `test-when-condition-6`, `test-when-condition-7` I'm using the same `pattern` variations but now the `matches` is part of an `and` statement list. I thought it might help. Does not work as well :(

For `test-when-condition-8`, `test-when-condition-9`, `test-when-condition-10`, `test-when-condition-11`, `test-when-condition-12`, `test-when-condition-13` I'm following the same strategy for `pattern` like above but now using a json-like structure for `matches` because your documentation about [logic statements](https://circleci.com/docs/2.0/configuration-reference/#logic-statements) provides this as an example. As you can guess, this does not work as well.

I even tried using `^\\d+\\.\\d+\\.\\d+$` (with escaped backslashes `\`) as a `pattern` because this is the Java-style you recommend in your docs about [logic statements](https://circleci.com/docs/2.0/configuration-reference/#logic-statements). However, no success.

Any ideas what I'm doing wrong?

## Note about the pattern

I'm pretty sure that the `pattern` of `\d+.\d+.\d+` for matching Git tags like `1.2.3` is working because I'm already using it with `filters` for single jobs like this:

```
version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - init:
          filters:
            tags:
              only:
                - /^\d+.\d+.\d+$/
            branches:
              ignore:
                - /.*/
```

This ensures my `init` job is only executed after a Git tag was added.

# Location
The bug occurs when I add the `when` conditions to my `.circleci/config.yml`. I'm using a GitHub repository connected to CircleCI.

# Steps to Reproduce
See description above :)

**Comment by thomasr8** [comment]
Hi @iwt-sebastian-hesse-extern : Thank you for reaching out to us about this issue. I am going to work with our Engineering and Support teams to find a solution for you.

**Comment by kelvintaywl** [comment]
hi @iwt-sebastian-hesse-extern !

Thanks for the detailed report!

For conditions on workflows, I believe you may need the `and` or `or` stanza before the `matches` expression.
In other words, your example for 5 and 7 should have worked, based on our documentation below
 https://circleci.com/docs/2.0/configuration-reference/#logic-statement-examples

Just to be sure, could you try to update pattern 5 with double-quotes, and see if it works for you?

```diff
  test-when-condition-5:
    when:
      and:
        - matches:
-            pattern: '^\d+.\d+.\d+$'
+            pattern: "^\d+.\d+.\d+$"
            value: << pipeline.git.tag >>
    jobs:
      - init
```

Also, to debug this, could you check the failed build and verify that this build was triggered via a git tag event?
<img width="1293" alt="Screen Shot 2022-02-16 at 14 00 54" src="https://user-images.githubusercontent.com/2164346/154199420-64ec6924-48e2-431e-a7b2-436c54a6102e.png">



If so, the << pipeline.git.tag >> value should exist, and that we should see the `CIRCLE_TAG` env var injected under the **Preparing Environment Variables** step indeed.
Example: https://app.circleci.com/pipelines/github/kelvintaywl/k-h-/40/workflows/afbb094c-ac8b-4607-bba0-0f73fb50f621/jobs/100?invite=true#step-99-19

**Comment by rosieyohannan** [comment]
Hi @iwt-sebastian-hesse-extern thanks for your help with this - can you also confirm that the git tag and `CIRCLE_TAG` definitely exist in the broken build output (2nd part of Kelvin's message) just so we've covered everything. Thank you! :-D

**Comment by iwt-sebastian-hesse-extern** [comment]
Hi @rosieyohannan , yes they definitely exist but I can only confirm that if I remove the `when` condition for my workflow. Because, as mentioned, using the `when` condition doesn't trigger my workflow and in this case, I can't verify that there are any environment variables. Does that make sense to you?

**Comment by rosieyohannan** [comment]
@iwt-sebastian-hesse-extern hello! So sorry for the delay here. We have an investigation going on for this issue. I'll update when we have news on whether there is a problem with filtering using tags, or if we have incorrect documentation. Thank you again for getting in touch about this! Also, here is a related thread: https://discuss.circleci.com/t/use-of-pipeline-git-tag-in-workflows-name-when/36159.

**Comment by akruchenkov** [comment]
Hi @rosieyohannan
This problem is still relevant and the tags do not work, I also tried other default parameters like a `pipeline.number`, and they also do not work, when can I expect a solution to this problem?
But it definitely works with parameters like `pipeline.parameters.my-parameter` and with `pipeline.git.branch`
My config.yml for tests is:
```
workflows:
  build-workflow:
    when:
      or:
        - matches:
            pattern: "1.1.5"
            value: << pipeline.git.tag >>
        - matches:
            pattern: '1.1.5'
            value: << pipeline.git.tag >>
        - matches:
            pattern: '^1.1.5$'
            value: << pipeline.git.tag >>
        - matches:
            pattern: "^1.1.5$"
            value: << pipeline.git.tag >>
        - matches:
            pattern: "^\\d+.\\d+.\\d+$"
            value: << pipeline.git.tag >>
        - matches:
            pattern: '^\d+.\d+.\d+$'
            value: << pipeline.git.tag >>
        - matches:
            pattern: "21"
            value: << pipeline.number >>
        - equal: [ "21", << pipeline.number >> ]
        - equal: [ 21, << pipeline.number >> ]
    jobs:
      - build
      - deploy
```
And that's what I see in the GUI:
![image](https://user-images.githubusercontent.com/97592084/183389689-c9d79eeb-d5f9-48bd-bfbd-46feefacab1a.png)
