### ISSUE TITLE
Python package caching example instructions are incorrect

### ISSUE THREAD

**Issue by awbacker** [circleci/circleci-docs#6409]
# Locations
https://circleci.com/docs/2.0/language-python/#cache-dependencies

# Details
The documentation for how to cache a virtualenv list incorrect locations.  The 3 locations listed as "to be cached" are:

```
- ".venv"
- "/usr/local/bin"
- "/usr/local/lib/python3.6/site-packages"
```

The rest of the examples list 3.10 as the python version, and also use `pipenv`.  The use of `pipenv` in the example does not use `--system`, so that wouldn't even install in the listed directory in the case it was actually 3.6 and not 3.10. 

The location for the site packages is no longer as listed in that example.  For some reason `/usr/local/lib` does have py2.7 and 3.8 in the latest python images, from the system python.

As the images now use pyenv, the default pip installs go to
> `/home/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages`

But this is also not good, it can't be restored for permission reasons.

* Why cache `/usr/local/bin`?
* `pipenv` does not create a `.venv`, it creates one in `/home/circleci/.local/share/virtualenvs/`

It is good to have an example of caching, but I don't think what is there is helpful.  It is probably counterproductive.  

I'm not sure exactly what to do about it, but the it should at least be consistent.  If the text uses pipenv (without --system) then have the example cache the right directory.  Perhaps add additional notes for other use cases here, at least the standard ones (pip install, python -m venv .venv). 

### Pyenv

The image uses pyenv.  Thats fine, but it doesn't include `pyenv-virtualenv`! which would seem logical.  If that was the encouraged method, then some standardized instructions and caching logic could be developed

Overall, python needs virtualenvs in this use case, and it would be great if the docs handled this correctly.  In the end I settled on this:

```
restore_cache:
    key: pyc-0007-{{ checksum "common.txt" }}

# container uses sh, so `.` required in place of `source`
run:
  name: Configure Container & Virtualenv
  command: |
      python -m venv venv-project
      . venv-project/bin/activate 
      pip install --upgrade pip setuptools wheel

save_cache:
    key: pyc-0007-{{ checksum "common.txt" }}
    paths:
      - "venv-project"
```
