### ISSUE TITLE
Using Android Images with the Machine Executor - Start Emulator Step is blocked by "emulator is out of date, please update by launching Android Studio"

### ISSUE THREAD

**Issue by bryanvaldellonsdet** [circleci/circleci-docs#6436]
# Description
Using Android Images with the Machine Executor - Start Emulator Step is blocked by "emulator is out of date, please update by launching Android Studio"

# Location
Tried to use this - https://circleci.com/docs/2.0/android-machine-image/

# Steps to Reproduce
1. Edited our yml file from - https://circleci.com/docs/2.0/android-machine-image/
2. used the simple orb usage
![image](https://user-images.githubusercontent.com/93500748/155914674-a513a791-b075-40c7-b3cc-d8e8bb5bd725.png)
![image](https://user-images.githubusercontent.com/93500748/155914710-0a85b19b-b41b-4a39-b980-c031e9860b92.png)

**Comment by felicianotech** [comment]
Hi @bryanvaldellonsdet, which image tag for the Android machine image are you using?

**Comment by bryanvaldellonsdet** [comment]
Hello @felicianotech, see below i hope i provided the image tag that you need

here's the orb i used
```
orbs:
  android: circleci/android@1.0.3
```

and this is the job

```
linux-android:
    parameters:
      tags:
        type: string
    executor:
      name: android/android-machine
    resource_class: large
    steps:
      - checkout # Checkout the code as the first step.
      - browser-tools/install-chrome
      - android/create-avd:
          avd-name: myavd
          system-image: system-images;android-29;default;x86
          install: true
      # By default, after starting up the emulator, a cache will be restored,
      # "./gradlew assembleDebugAndroidTest" will be run and then a script
      # will be run to wait for the emulator to start up.
      # Specify the "post-emulator-launch-assemble-command" command to override
      # the gradle command run, or set "wait-for-emulator" to false to disable
      # waiting for the emulator altogether.
      - android/start-emulator:
          avd-name: myavd
          no-window: true
          restore-gradle-cache-prefix: v1a
      # Runs "./gradlew connectedDebugAndroidTest" by default.
      # Specify the "test-command" parameter to customize the command run.
      - android/run-tests
      - android/save-gradle-cache:
          cache-prefix: v1a
```
