### ISSUE TITLE
docker authentication with AWS ECR using CIRCLE_OIDC_TOKEN

### ISSUE THREAD

**Issue by jsab** [circleci/circleci-docs#6574]
# Missing Information
How to use CIRCLE_OIDC_TOKEN to authenticate with AWS ECR to use private images in a docker executor.

It appears only authentication using aws_access_key/secret_access_key is documented.

Expecting something like:
```yaml
    docker:
      - image: account-id.dkr.ecr.us-east-1.amazonaws.com/org/repo:0.1
        aws_auth:
          aws_web_identity_token: $CIRCLE_OIDC_TOKEN
```

# Already Looked
https://circleci.com/docs/2.0/private-images/

# Potential Locations
https://circleci.com/docs/2.0/private-images/
