### ISSUE TITLE
Running steps in parallel (NOT tests, setup steps)

### ISSUE THREAD

**Issue by goldylucks** [circleci/circleci-docs#6699]
# Missing Information
I want to be able to do something like the following:

```
commands:
  - setup:
     parallel: true
     steps:
        - run ...
        - run ...
        - run ...
```

# Already Looked
Googled and searched in the docs, only found info about parallel tests

# Potential Locations
New document

#Note

I don't think running multiple parallel jobs and persisting/attaching to workspace will help, because the setup steps are not about our app's code, rather about the environment itself, so it would be very tricky to know what to persist/attach and where.

For context, our setup is:

```
# install ruby and compass gem
sudo apt update
sudo apt install ruby-dev -y
sudo gem install compass

# install ubuntu deps
sudo apt install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

# install npm deps
npm ci

# install bower deps
npx bower install
```

I'd like to do all of the above in parallel
