### ISSUE TITLE
can't connect to mongo (nx monorepo)

### ISSUE THREAD

**Issue by goldylucks** [circleci/circleci-docs#7220]
Don't know if this is related to nx or not

# Description
The node js application hans on connecting to the DB

# Location
using mongo

# Steps to Reproduce
- create fresh node project with nx
- add mongoose and connect to db
- try to spin up server (or tests)

```
# config.yml
version: 2.1

orbs:
  node: circleci/node@5.0.2
  nx: nrwl/nx@1.5.1

commands:
  bt-setup:
    steps:
      - checkout
      - bt-yarn-install

  bt-mongo:
    steps:
      - run:
          name: MongoDB Install
          command: |
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
            echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
            sudo apt-get update
            sudo apt-get install -y mongodb-org-shell
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Dockerize Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run:
          name: Get versions
          command: |
            node -v
            npm -v
            mongo --version
            mongo localhost --eval "db.version()"
      - run:
          name: Connect to DB
          command: mongo --eval "printjson(db.apikeys.count());" localhost

  bt-yarn-install:
    steps:
      - node/install-packages:
          pkg-manager: yarn

jobs:
  test-api:
    docker:
      - image: cimg/node:lts-browsers
      - image: mongo:4.4.14
    environment:
      NX_CLOUD_DISTRIBUTED_EXECUTION: "true"
    steps:
      - bt-setup
      - bt-mongo
      - run:
          name: Run Tests
          command: |
            MONGODB_URI=mongodb://127.0.0.1:27017/localhost IS_CI_TEST=true yarn test:api --run-in-band

workflows:
  build:
    jobs:
      - test-api
```

The server:
```
mongoose
      .connect(process.env.MONGODB_URI, {
        // doesn't work on heroku :/
        // autoEncryption: this.autoEncryption,
      })
      .then(console.log)
      .catch(console.error)
```

this hangs and doesn't output anything
