### ISSUE TITLE
aws-cli/configure error for this example with ecs

### ISSUE THREAD

**Issue by carlostrice** [circleci/circleci-docs#7245]
# Locations
https://circleci.com/docs/deploy-service-update-to-aws-ec2#full-config

# Details
Error calling workflow: 'build-and-deploy'Error calling job: 'verify-deployment'Cannot find a definition for command named aws-cli/configure

**Comment by devinmarieb** [comment]
@carlostrice Hi thanks for bringing this up. It looks like this example needed an update with some new versions and naming conventions. The following is an updated version of this example that is running as valid config in our app:

```
version: 2.1 # 2.1 config required to use orbs

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2 # use the AWS ECR orb
  aws-ecs: circleci/aws-ecs@3.0.0 # use the AWS ECS orb
  aws-cli: circleci/aws-cli@3.1.1 # use the AWS CLI orb

jobs:
  verify-deployment:
    executor: aws-cli/default
    steps:
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_DEFAULT_REGION
      - run:
          name: Get last task definition
          command: >
            TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                --task-definition ${MY_APP_PREFIX}-service \
                --output text \
                --query 'taskDefinition.taskDefinitionArn')
            echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >>
            $BASH_ENV
      - aws-ecs/verify-revision-is-deployed:
          family: '${MY_APP_PREFIX}-service'
          cluster: '${MY_APP_PREFIX}-cluster'
          task-definition-arn: '${TASK_DEFINITION_ARN}'

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image: # orb built-in job
          repo: '${MY_APP_PREFIX}'
          tag: '${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update: # orb built-in job
          requires:
            - aws-ecr/build-and-push-image
          family: '${MY_APP_PREFIX}-service'
          cluster: '${MY_APP_PREFIX}-cluster'
          container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
      - verify-deployment:
          requires:
            - aws-ecs/deploy-service-update
```

The changes are:

`aws-ecs: circleci/aws-ecs@2.1.1` ➡️  `aws-ecs: circleci/aws-ecs@3.0.0`

```
- aws-cli/configure:
    aws-access-key-id: $AWS_ACCESS_KEY_ID
    aws-region: $AWS_REGION
```
⬇️ 
```
- aws-cli/setup:
    aws-access-key-id: AWS_SECRET_ACCESS_KEY
    aws-region: AWS_DEFAULT_REGION
    aws-secret-access-key: AWS_DEFAULT_REGION
```

instances of `cluster-name:` ➡️ `cluster:`

I will open a ticket to look at other instances where these may need to be updated. Thank you!
