### ISSUE TITLE
List "not" conditionals do not work as expected

### ISSUE THREAD

**Issue by seand7565** [circleci/circleci-docs#7246]
# Description
The `not` conditional normally will accept 1 parameter, such as:

```yaml
version: 2.1

workflows:
  test-workflow:
    when:
      not:
        equal: [ master, << pipeline.git.branch >> ]
```

However, try as I might, I have not been able to get `not` to accept any parameters when it is in a list:

```yaml
version: 2.1

parameters:
  run_specs_on_main_branch:
    type: boolean
    default: false

workflows:
  test-and-lint:
    when:
      or:
        - << pipeline.parameters.run_specs_on_main_branch >>
        - not:
          # This does not work, validation error is:
          # `Object has more properties than limit of 1`
          equal: [ master, << pipeline.git.branch >> ]
        # Or, trying it with equal as a list:
        - not:
          # This also does not work, validation error is:
          # `Incorrect type. Expected one of string, boolean, integer, number.`
          - equal: [ master, << pipeline.git.branch >> ]
```

The specific use-case for this is: If I want this workflow to run on master **only** if a parameter is provided, but it can run freely on other branches. Useful for us, for running specs on all branches before merging, and setting up a scheduled spec run on master (without needing to run specs on every deploy).

The only way I could get this to work is by doing the following, very ugly negative lookahead:

```yaml
version: 2.1

parameters:
  run_specs_on_main_branch:
    type: boolean
    default: false

workflows:
  test-and-lint:
    when:
      or:
        - and:
          - equal: [ master, << pipeline.git.branch >> ]
          - << pipeline.parameters.run_specs_on_main_branch >>
        # This monstrosity is a negative lookahead - basically matching any string that
        # is not master. Necessary because circle doesn't allow for list nots with parameters.
        - matches: { pattern: "^((?!master).)*$", value: << pipeline.git.branch >> }
```

Curious if I missed some obvious way to do this, or if it's a legitimate bug. I would expect `not` to have the same behavior as a list item that it does as a non list item.

**Comment by kbatuigas** [comment]
Hi, @seand7565 - thanks for your patience here. I relayed your question to our engineering team and it sounds like another workaround you could look into is to define two workflows. The first workflow defines a `when` and each job has a branch filter to only run on master. The second workflow doesn't define a `when`, and has a branch filter that ignores master.

```
workflows:
  master-only:
    when:
      ...
    jobs:
      - job1:
          filters:
            branches:
              only:
                master
      - job2:
          filters:
            branches:
              only:
                master

  branches-only:
    jobs:
      - job1:
          filters:
            branches:
              ignore:
                - master
      - job2:
          filters:
            branches:
              ignore:
                - master
```

The caveat is that it could also be hard to maintain, and isn't necessarily a more elegant way, but perhaps something to consider?

**Comment by seand7565** [comment]
Hey @kbatuigas thanks for the feedback! TBH I'd prefer the ugly regex to defining the job twice, as it's a pretty big job. 😛 

I'm not sure, given the response, if this is considered a bug by the eng team or not? If it's not, I think the action item here would be to notate this in the circleCI docs to avoid future confusion.

**Comment by kbatuigas** [comment]
Hey @seand7565 ! Just to double check, in your first failing example, does further indenting the `equal` resolve things? i.e.

```
- not:
    # This does not work, validation error is:
    # `Object has more properties than limit of 1`
    equal: [ master, << pipeline.git.branch >> ]
```

**Comment by seand7565** [comment]
Surprisingly yes! I did not know double tabbing non-list items under a list item was necessary, but I guess that was the missing piece here? Thanks.

WDYT about changing the last example in the [conditional doc](https://support.circleci.com/hc/en-us/articles/360043638052-Conditional-steps-in-jobs-and-conditional-workflows) to include this use case? Something like this maybe:

```yml
- when:
    condition:
      or:
        - and:
          - or:
              - and:
                  - equal: [ main, << pipeline.git.branch >> ]
                  - equal: [ false, << pipeline.parameters.param1 >> ]
              - or:
                  - not: << pipeline.parameters.param3 >>
                  - not:
                      equal: [ testbranch, << pipeline.git.branch >> ] # <-- Added this one
          - or:
              - equal: [ false, << pipeline.parameters.param3 >> ]
              - or: [ << pipeline.parameters.param1 >>, << pipeline.parameters.param2 >> ]  
        - or:
            - equal: [ true, << pipeline.parameters.param4 >> ]

    steps:
      - run: echo "param 4 is true OR the other nested conditions are true"
```

Just to prevent a future version of me from becoming confused?
