### ISSUE TITLE
Dynamic configurations with multiple continue jobs fails

### ISSUE THREAD

**Issue by vincentmrg** [circleci/circleci-docs#7550]
# Description
Hello,

I tried to use the dynamic configuration feature in order to run two workflows in parallel.
In this scenario, only one of the workflows is executed, the other fails with a `{"message":"Pipeline is not in setup state."}` error.
It seems that at the execution of the first "continue" job, the status of the pipeline is changed and prevents the execution of the 2nd one.

<img width="335" alt="Screenshot 2022-11-09 at 18 43 58" src="https://user-images.githubusercontent.com/24724195/200902434-09d7282d-3bf2-4252-b16d-1c24921484d5.png">

# Location
I found this bug when I was implementing dynamic configuration. I was referring https://circleci.com/docs/dynamic-config/ and https://circleci.com/docs/using-dynamic-configuration/

# Steps to Reproduce
1. Create a `.circleci/deploy.yml` with a "deployment" workflow
2. Create a `.circleci/config.yml` with the following setup configuration

```yml
version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the continuation orb is required in order to use dynamic configuration
orbs:
  continuation: circleci/continuation@0.1.2

# our defined job, and its steps
jobs:
  deploy:
    executor: continuation/default
    parameters:
      environment:
        type: string
        description: Which environment to deploy
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/deploy.yml
          parameters: .circleci/env/<< parameters.environment >>.json

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    jobs:
      - deploy:
          matrix:
            parameters:
              environment:
                - "eu-west-1"
                - "eu-west-3"

```
