### ISSUE TITLE
Manual Allocation of Parallelism does not work

### ISSUE THREAD

**Issue by srqdeveloper** [circleci/circleci-docs#7833]
# Locations
Add a link to the document
with the incorrect information.
https://circleci.com/docs/parallelism-faster-jobs/#manual-allocation

# Details
Describe the incorrect information in the document.
Extra evidence like build output or other links
is helpful in "proving" that documentation isn't correct.
![image](https://user-images.githubusercontent.com/7866684/223223661-1d9013ab-e9ad-49f9-ab88-8844c4e79108.png)

AFFECTED_PROJECTS=$(echo "project1, project2, project-3" | sed 's/, /\n/g' | circleci tests split --total=3)

This run shows the total flag being passed, but it having no effect on the number of containers generated. The split algorithm still works to only put one project in the container, but no parallel containers are generated.

When we raised this issue to some folks in support, I believe they confirmed it did not work and the documentation was out of date.

**Comment by rosieyohannan** [comment]
Hello! Thanks for getting in touch about this. Is there any chance you can share your config file? or the full job config so I can get a clearer idea of where the issue is? Thank you!

I think the issue is that the doc is unclear, rather than manual allocation being outdated. Have you set the `parallelism` key in your config? https://circleci.com/docs/configuration-reference/#parallelism

**Comment by srqdeveloper** [comment]
We have had success using the `parallelism` key, yes. I'll double check with an example of using the `parallelism` key and the `--total` flag together to see if `--total` will override the `parallelism` value. I definitely did not have success using just the `--total` flag. If that still does not work, I'll see if I can post an example config.

**Comment by srqdeveloper** [comment]
I have tried an example with the bare bones `config.yml` below. The `--total=22` has no effect on the parallelism value. The jobs is parallelized with only 10 containers. Parallelism does not work at all if the parallelism key is removed from the job config.

```
version: 2.1

jobs:
  total:
    docker:
      - image: cimg/node:16.18.1
    resource_class: small
    parallelism: 10
    steps:
      - run:
          name: Split into containers
          command: |
printf "test1\ntest2\ntest3\ntest4\ntest5\ntest6\ntest7\ntest7\ntest9\ntest10\ntest11\ntest12\ntest13\ntest14\ntest15\ntest16\ntest17\ntest18\ntest19\ntest20\ntest21\ntest22" | circleci tests split --total=22

workflows:
  setup:
    jobs:
      - total

```

![image](https://user-images.githubusercontent.com/7866684/230676680-50f8888b-7a36-4c14-9589-c328122cf539.png)
