### ISSUE TITLE
Can we specify `when:` within the `workflows` mapping?

### ISSUE THREAD

**Issue by thomasmatecki** [circleci/circleci-docs#7857]
# Locations
This issue is in a blog post:
[Trigger your CircleCI pipelines from a GitHub Actions workflow](https://circleci.com/blog/trigger-circleci-pipeline-github-action/)

This is probably not the best place to raise this issue, but I can't find another channel.

# Details
The blog provides this snippet of config to conditionally run circle CI pipelines:
```
workflows:
  # This workflow is set to be triggered conditionally, only when
  # the GitHub Action is triggered.
  # With no other workflows, normal push events will be ignored.
  when: << pipeline.parameters.GHA_Action >>
  test:
    jobs:
      - test
```

... but this doesn't seem to be valid ... 

The error I get is:
```
Error: ERROR IN CONFIG FILE:
[#/workflows/when] only 0 subschema matches out of 2
1. [#/workflows/when] expected type: Mapping, found: String
|   SCHEMA:
|     type: object
|   INPUT:
|     << pipeline.parameters.GHA_Action >>
2. [#/workflows/when] subject must not be valid against schema {"description":"cannot use both 'when' and 'unless'","allOf":[{"required":["when"]},{"required":["unless"]}]}
|   SCHEMA:
|     not:
|       description: cannot use both 'when' and 'unless'
|       allOf:
|       - required:
|         - when
|       - required:
|         - unless
|   INPUT:
|     << pipeline.parameters.GHA_Action >>
CircleCI Configuration Failed Validation.
```

By guess is that supplying `when` under `workflows` is not allowed, but the schema validation seems to allude to some different problem? I guess either _it is possible to define a top level `when` clause_ and the validation is wrong or the blog is wrong.

**Comment by rosieyohannan** [comment]
Hello @thomasmatecki! Thanks so much for letting us know about this. We have this section on using `when` in workflows: https://circleci.com/docs/configuration-reference/#using-when-in-workflows ... Taking a quick look I think maybe it's just an error in the snippet, and the workflow name comes first before `when`. I will check this and get back to you :-D

**Comment by rosieyohannan** [comment]
So this will work (as long as the pipeline parameter `GHA_Action` is defines in the config too):

```
workflows:
  test:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - test
 ```
