### ISSUE TITLE
Make 'requires' do not ignore dependent job when the job from the list failed or add a new key for this purpose

### ISSUE THREAD

**Issue by NadzeyaSam** [circleci/circleci-docs#7981]
```
workflows:
  build-and-deploy:
       jobs:
          - deploy-service-update:
                    name: deploy-to-dev
                     .....
          - notify:
                    ......
                    requires:
                      - deploy-to-dev
```
When `deploy-to-dev` fails, `notify` ignored.
