### ISSUE TITLE
How to target Jira tickets when deploying from a Git tag

### ISSUE THREAD

**Issue by gazpachu** [circleci/circleci-docs#8305]
# Missing Information
When deploying from a Git tag, the Jira ticket IDs are not present on the commit details or PR. How can we tell Jira to update those tickets that were deployed from a tag?

With PRs/commits, we can use `scan_commit_body: true`, but for tags, it's unclear how to achieve a similar outcome. This is an important caveat, since most production deployments are usually triggered from Git tags, rather than branches.

Example for Git branches:
```
- deploy-product-staging:
   context: lprd
      post-steps:
        - jira/notify:
            environment: product-staging
            environment_type: staging
            job_type: deployment
            scan_commit_body: true
```

# Already Looked
- https://circleci.com/developer/orbs/orb/circleci/jira
- https://circleci.com/docs/jira-plugin/

# Potential Locations
- https://circleci.com/developer/orbs/orb/circleci/jira
- https://circleci.com/docs/jira-plugin/
