### ISSUE TITLE
<<pipeline.git.tag>> is no longer working to trigger when step

### ISSUE THREAD

**Issue by bgould-careplanner** [circleci/circleci-docs#8748]
# Description
When using the pipeline.git.tag which should be an empty string as declared by the docs this step then doesn't run.
```
      - when:
          condition:
            equal:
              - ""
              - <<pipeline.git.tag>>
          steps:
            - run: <your command here>
```
# Location

Running a pipeline with the above code block. Which worked previously and seemed to stop working may 1st around 3:00 UTC

Docs:
https://circleci.com/docs/pipeline-variables/#pipeline-parameters-in-configuration:~:text=%2C%20bitbucket.-,pipeline.git.tag,-GitHub%20App%2C%20GitHub

Unsure if something in the docs has changed but just not been reflected

# Steps to Reproduce
Describe the steps you took to produce the bug.
Run a job with a git branch and the above step should run

Run with a tag and this step then doesn't run
