### ISSUE TITLE
project-walkthrough: save_cache paths for python leads to "Command not found" in next builds

### ISSUE THREAD

**Issue by blurrcat** [circleci/circleci-docs#917]
In the [project-walkthrough](https://circleci.com/docs/2.0/project-walkthrough/), it is suggested to cache the following directories for Python projects:
- `~/.cache/pip`
- `/usr/local/lib/python3.6/site-packages`

This leads to errors like `flake8: Command not found` in next builds. With the cache in place, pip thinks flake8 is already installed while the `bin` directory is not restored.

To fix this, one can create a virtualenv and cache it, just like in circle 1:
```yml
 - restore_cache: v1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
 - run: |
     python3 -m venv ~/venv
     . ~/venv/bin/activate
     pip install requirements/dev.txt
 - run: |
     . ~/venv/bin/activate
     make test
- save_cache:
    key: v1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
    paths:
      - "~/.pip/cache"
      - "~/venv"
```
