### ISSUE TITLE
The indentation looks incorrect for the YAML snippet

### ISSUE THREAD

**Issue by peter-smith-phd** [circleci/circleci-docs#9310]
# Location
[A link to the document with the typo.](https://circleci.com/docs/slack-orb-tutorial/#use-message-templates)

# Error Details
In the YAML example, the indentation of the steps seems wrong:

```
jobs:
  notify:
    docker:
      - image: cimg/base:current
    steps:
- slack/notify:
	  event: fail
	  template: basic_fail_1
- slack/notify:
	  event: pass
	  template: success_tagged_deploy_1
```
