### ISSUE TITLE
CircleCI 2 caching - Add what-can-be-cached, howto cache and examples for source caching

### ISSUE THREAD

**Issue by kenden** [circleci/circleci-docs#997]
On this page 
https://circleci.com/docs/2.0/caching/

The intro explains what caching is.

* It would also be nice to add a section about what can be cached:
  - the source code 
  - the dependencies of an app (librairies)
  - docker layer caching (add a link to https://circleci.com/docs/2.0/docker-layer-caching/)
  - ...

* I am missing something about how to create a cache.
  There is only information about restoring a cache, not restoring.
  Also, add this link? https://circleci.com/docs/2.0/configuration-reference/#savecache

* I would also be nice to add an example for source caching (probably for other types of caching too, but I'm trying to do source caching, so that's what I currently miss).
Something like this?
  ```yaml
  jobs:
    build:
      working_directory: ~/src
      docker:
        - image: openjdk:8u121-jdk
      steps:
        - restore_cache:
            key: v1-my-app  # match any keys *starting with* 'v1-my-app'
        - checkout
        - run: echo "Test source caching"
        - save_cache:
            key: v1-my-app-{{ .BuildNum }}  # save the latest changes
            paths:
              - ~/src  # folder which should be added to the cache, here, the whole working dir.
  ```

  `~/src` has to match in working_directory and save_cache.paths
  Also, add link to this page?
  https://circleci.com/docs/2.0/configuration-reference/#restore_cache
