### ISSUE TITLE
In config reference, indicate where branches.only goes

### ISSUE THREAD

**Issue by kenden** [circleci/circleci-docs#999]
In this page:
https://circleci.com/docs/2.0/configuration-reference/#branches
it says to add:
```yaml
branches:
  only:
    - master
    - /rc-.*/
```

to the config.yml file.

It would be nice to know where.
It goes under jobs.build.

## Replace with:

```yaml
jobs:
  build:
    branches:
      only:
        - master
        - /rc-.*/
```
